//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset_AssetMoveDocDetail
    {
        public int AssetMovDetailId { get; set; }
        public Nullable<int> AssetMovId { get; set; }
        public Nullable<int> AssetId { get; set; }
        public Nullable<int> OldStoreId { get; set; }
        public Nullable<int> NewStoreId { get; set; }
        public Nullable<int> OldDepartMentId { get; set; }
        public Nullable<int> NewDepartMentId { get; set; }
        public Nullable<decimal> MoveCost { get; set; }
    }
}
