//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset_AssetDeductDocDetail
    {
        public int DeductAssetDetailId { get; set; }
        public Nullable<int> AssetDeductId { get; set; }
        public Nullable<int> AssetId { get; set; }
        public Nullable<int> AssetAccountId { get; set; }
        public Nullable<int> CostCenterId { get; set; }
        public Nullable<decimal> DeductValue { get; set; }
        public string Remarks { get; set; }
        public string Remarks1 { get; set; }
        public string Remarks2 { get; set; }
        public string Remarks3 { get; set; }
    }
}
