//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset_AssetSettingDetails
    {
        public int AssetSetDetails { get; set; }
        public Nullable<int> AssetSetId { get; set; }
        public Nullable<int> AssetId { get; set; }
        public Nullable<System.DateTime> DeprStartDate { get; set; }
        public Nullable<decimal> UsablifeTime { get; set; }
        public Nullable<decimal> ScrapValu { get; set; }
        public string Remarks1 { get; set; }
        public string Remarks2 { get; set; }
        public string Remarks3 { get; set; }
        public string Remarks4 { get; set; }
    }
}
