//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset_AssetCard
    {
        public int AssetId { get; set; }
        public Nullable<int> AssetCatId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> CostCenterId { get; set; }
        public Nullable<int> CostCenterId2 { get; set; }
        public Nullable<int> CostCenterId3 { get; set; }
        public Nullable<int> DepartMentId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> CurrentEmpId { get; set; }
        public string AssetCode { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public Nullable<bool> NoDepreciation { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<System.DateTime> PurchDate { get; set; }
        public string PurchDoc { get; set; }
        public string VendorDesc { get; set; }
        public string SerialNo { get; set; }
        public string WarrantyTerms { get; set; }
        public Nullable<System.DateTime> WarrantyDate { get; set; }
        public string WarrantyNo { get; set; }
        public Nullable<System.DateTime> InsuranceExpiry { get; set; }
        public string ResponsiblePerson { get; set; }
        public Nullable<decimal> MarketPrice { get; set; }
        public Nullable<byte> Barcode { get; set; }
        public Nullable<decimal> PurchPrice { get; set; }
        public Nullable<System.DateTime> LastDeprDate { get; set; }
        public Nullable<System.DateTime> DeprStartDate { get; set; }
        public Nullable<decimal> DeprInstallmentVal { get; set; }
        public Nullable<int> InstallMentCount { get; set; }
        public Nullable<int> RemainInstallments { get; set; }
        public Nullable<byte> DeprMethod { get; set; }
        public Nullable<decimal> ProductivPeriod { get; set; }
        public Nullable<decimal> CurrentBookValue { get; set; }
        public Nullable<decimal> JunkValue { get; set; }
        public Nullable<bool> IsProduction { get; set; }
        public Nullable<int> EquipId { get; set; }
        public string CarLicenseNo { get; set; }
        public Nullable<System.DateTime> CarLicenseIssueDate { get; set; }
        public string CarLicenseIssuePlace { get; set; }
        public Nullable<System.DateTime> CarLicenseExpiryDate { get; set; }
        public Nullable<System.DateTime> dtReg { get; set; }
        public Nullable<System.DateTime> dtRegRenew { get; set; }
        public string Address { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Remarks { get; set; }
        public string Tel { get; set; }
        public string Tel2 { get; set; }
        public string Tel3 { get; set; }
        public string Tel4 { get; set; }
        public string Tel5 { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Email2 { get; set; }
        public string Email3 { get; set; }
        public string Email4 { get; set; }
        public string AddField1 { get; set; }
        public string AddField2 { get; set; }
        public string AddField3 { get; set; }
        public string AddField4 { get; set; }
        public string AddField5 { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    }
}
