//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class BNK_BankNoticeDetail
    {
        public int BankNoticDetailId { get; set; }
        public Nullable<int> BankNoticId { get; set; }
        public Nullable<int> RectId { get; set; }
        public Nullable<int> PayId { get; set; }
        public Nullable<bool> IsCollected { get; set; }
        public Nullable<System.DateTime> CollectDate { get; set; }
        public Nullable<bool> IsReturned { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<bool> Canceled { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsTransferred { get; set; }
        public Nullable<System.DateTime> TransferredAte { get; set; }
    }
}
