//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cal_PostOrder
    {
        public int PostQueId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> CostCenterId { get; set; }
        public Nullable<bool> IsHelpAcc { get; set; }
        public Nullable<int> HelpAccId { get; set; }
        public string HelpAccType { get; set; }
        public Nullable<bool> IsHelpCostCenter { get; set; }
        public Nullable<int> HelpCostCenterId { get; set; }
        public string HelpCostCenterType { get; set; }
        public Nullable<int> TermId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> FinancialIntervalsId { get; set; }
        public Nullable<System.DateTime> OriginalDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string TableCode { get; set; }
        public Nullable<int> TableEntityId { get; set; }
        public Nullable<decimal> DebitLocal { get; set; }
        public Nullable<decimal> CreditLocal { get; set; }
        public Nullable<decimal> OpenningBalanceDepit { get; set; }
        public Nullable<decimal> OpenningBalanceCredit { get; set; }
        public Nullable<decimal> BalaceLocalBeforDebit { get; set; }
        public Nullable<decimal> BalaceLocalBeforCredit { get; set; }
        public Nullable<decimal> BalanceLocalAfterDebit { get; set; }
        public Nullable<decimal> BalanceLocalAfterCredit { get; set; }
        public Nullable<decimal> DebitCurrency { get; set; }
        public Nullable<decimal> CreditCurrency { get; set; }
        public Nullable<decimal> OpenningBalanceDepitCurncy { get; set; }
        public Nullable<decimal> OpenningBalanceCreditCurncy { get; set; }
        public Nullable<decimal> BalaceCurrencyBeforDebit { get; set; }
        public Nullable<decimal> BalaceCurrencyBeforCredit { get; set; }
        public Nullable<decimal> BalanceCurrencyAfterDebit { get; set; }
        public Nullable<decimal> BalanceCurrencyAfterCredit { get; set; }
        public Nullable<decimal> OpenBalancDepCostCentr { get; set; }
        public Nullable<decimal> OpenBalancCredCostCentr { get; set; }
        public Nullable<decimal> BalancLocalBeforDebCostCentr { get; set; }
        public Nullable<decimal> BalancLocalBeforCredCostCentr { get; set; }
        public Nullable<decimal> BalancLocalAfterDebCostCentr { get; set; }
        public Nullable<decimal> BalancLocalAfterCredCostCentr { get; set; }
        public Nullable<decimal> OpenBalancDepCrncyCostCentr { get; set; }
        public Nullable<decimal> OpenBalancCredCrncyCostCentr { get; set; }
        public Nullable<decimal> BalancCrencyBeforDebtCostCentr { get; set; }
        public Nullable<decimal> BalancCrencyBeforCredCostCentr { get; set; }
        public Nullable<decimal> BalancCrencyAftrDebtCostCentr { get; set; }
        public Nullable<decimal> BalancCrencyAftrCredCostCentr { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<bool> IsOpenningTerm { get; set; }
    }
}
