//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cal_AccountClaasiJoin
    {
        public int AcChrtJoinClaasi { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> AccountClassId { get; set; }
        public Nullable<byte> Operator { get; set; }
        public Nullable<int> DaysCount { get; set; }
        public Nullable<byte> TypeOfAcc { get; set; }
    }
}
