//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cal_Budget
    {
        public int BudgetId { get; set; }
        public Nullable<int> StorId { get; set; }
        public Nullable<int> TermId { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<int> Aid { get; set; }
        public Nullable<int> FinancialIntervalsId { get; set; }
        public Nullable<int> FromFinancialIntervalsId { get; set; }
        public Nullable<int> ToFinancialIntervalsId { get; set; }
        public string ScinarioDesc { get; set; }
        public Nullable<int> TrNo { get; set; }
        public string ManualTrNo { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public string Postedby { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<int> ShiftId { get; set; }
    }
}
