//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cal_BudgetDetails
    {
        public int BudgetDetailId { get; set; }
        public Nullable<int> BudgetId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> FromFinancialIntervalsId { get; set; }
        public Nullable<int> ToFinancialIntervalsId { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<int> CostCenterId { get; set; }
        public string Remarks { get; set; }
    }
}
