//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cal_AccountUsers
    {
        public int AccUserId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public string Remarks1 { get; set; }
        public string Remarks2 { get; set; }
        public Nullable<bool> TranAndView { get; set; }
    }
}
