//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cod_PackingSize
    {
        public int PackSizeId { get; set; }
        public int Code { get; set; }
        public string DescA { get; set; }
        public string DescE { get; set; }
        public Nullable<int> AId { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Hieght { get; set; }
        public Nullable<decimal> LengthMeter { get; set; }
        public Nullable<decimal> LengthCentimeter { get; set; }
        public Nullable<decimal> LengthMillimeters { get; set; }
        public Nullable<decimal> WidthMeter { get; set; }
        public Nullable<decimal> WidthCentimeter { get; set; }
        public Nullable<decimal> WidthMillimeters { get; set; }
        public Nullable<decimal> HeightMeter { get; set; }
        public Nullable<decimal> HeightCentimeter { get; set; }
        public Nullable<decimal> HeightMillimeters { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> Wheight { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public string RemarksA { get; set; }
        public string RemarksE { get; set; }
    }
}
