//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cod_InstallmentTempsDetail
    {
        public int InstallTempDetailId { get; set; }
        public Nullable<int> InstallTempId { get; set; }
        public Nullable<int> PayTypeId { get; set; }
        public Nullable<int> PayCount { get; set; }
        public Nullable<int> PayRepeat { get; set; }
        public Nullable<int> YearOrder { get; set; }
        public Nullable<int> MonthOrder { get; set; }
        public Nullable<decimal> PayValue { get; set; }
        public Nullable<decimal> PayPercent { get; set; }
        public Nullable<decimal> TotalValue { get; set; }
        public Nullable<int> MonthOfInstall { get; set; }
        public string Remarks1 { get; set; }
        public string Remarks2 { get; set; }
    }
}
