//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cod_LandPosJoin
    {
        public int LandPosJoinId { get; set; }
        public Nullable<int> LandId { get; set; }
        public Nullable<int> LandPosId { get; set; }
        public string Remarks1 { get; set; }
        public string Remarks2 { get; set; }
    }
}
