//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_TeamMembers
    {
        public int TeamMemberId { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string MemberCode { get; set; }
        public string MemberName1 { get; set; }
        public string MemberName2 { get; set; }
        public Nullable<bool> IsTeamLeader { get; set; }
        public Nullable<decimal> DefaultTarget { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string Remarks { get; set; }
        public string AddField1 { get; set; }
        public string AddField2 { get; set; }
        public string AddField3 { get; set; }
        public string AddField4 { get; set; }
        public string AddField5 { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    }
}
