//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_SurveyMemberJoin
    {
        public int SurveyVisitId { get; set; }
        public Nullable<int> SurveyId { get; set; }
        public Nullable<int> TeamMemberId { get; set; }
    }
}
