//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_AlertControl
    {
        public int Compcode { get; set; }
        public string SystemCode { get; set; }
        public Nullable<bool> EMAIL_SSL { get; set; }
        public Nullable<bool> EMAIL_Authentication { get; set; }
        public string EMAIL_SenderName { get; set; }
        public string EMAIL_Sender { get; set; }
        public string EMAIL_SenderPassword { get; set; }
        public Nullable<int> EMAIL_SendorPort { get; set; }
        public string EMAIL_SenderSMTP { get; set; }
        public string SMS_Provider { get; set; }
        public string SMS_UserName { get; set; }
        public string SMS_SenderName { get; set; }
        public string SMS_Password { get; set; }
        public string MobileNoPreFex { get; set; }
        public Nullable<int> EmailMaxDaily { get; set; }
    }
}
