//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_AlertLog
    {
        public int AlertID { get; set; }
        public string AlertType { get; set; }
        public Nullable<int> TrID { get; set; }
        public Nullable<int> MsgType { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<bool> IsSent { get; set; }
        public string MsgHeader { get; set; }
        public string MsgBody { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string SystemCode { get; set; }
        public Nullable<int> CompCode { get; set; }
    }
}
