//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_AlertType
    {
        public string AlertType { get; set; }
        public string DescA { get; set; }
        public string DescE { get; set; }
        public string SystemCode { get; set; }
        public Nullable<int> CompCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
