//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_COMPANY
    {
        public int COMP_CODE { get; set; }
        public string NameA { get; set; }
        public string NameE { get; set; }
        public string Systems { get; set; }
        public string MOI_ID { get; set; }
        public string CRT_NO { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public string GMName { get; set; }
        public string HRResponsible { get; set; }
        public string FinanceResponsible { get; set; }
        public string SalesManager { get; set; }
        public string CUSTOM1 { get; set; }
        public string CUSTOM2 { get; set; }
        public string CUSTOM3 { get; set; }
        public string CUSTOM4 { get; set; }
        public string CUSTOM5 { get; set; }
        public Nullable<bool> CUSTOMFLAG1 { get; set; }
        public Nullable<bool> CUSTOMFLAG2 { get; set; }
        public Nullable<decimal> CUSTOMNUM1 { get; set; }
        public Nullable<decimal> CUSTOMNUM2 { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsReadOnly { get; set; }
        public string LogoIcon { get; set; }
        public string BkImage1 { get; set; }
        public string BkImage2 { get; set; }
        public string GroupVatNo { get; set; }
        public string VATNO { get; set; }
        public Nullable<int> VndIDTypeCode { get; set; }
        public string IDNo { get; set; }
        public string Address_Street { get; set; }
        public string Address_Str_Additional { get; set; }
        public string Address_BuildingNo { get; set; }
        public string Address_Build_Additional { get; set; }
        public string Address_City { get; set; }
        public string Address_Postal { get; set; }
        public string Address_Province { get; set; }
        public string Address_District { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public Nullable<int> Currencyid { get; set; }
    }
}
