//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_CONTROL
    {
        public int COMP_CODE { get; set; }
        public int FIN_YEAR { get; set; }
        public Nullable<short> ACC_STATUS { get; set; }
        public Nullable<short> INV_STATUS { get; set; }
        public Nullable<System.DateTime> FirstDate { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public string ProfitAcc_Code { get; set; }
        public Nullable<int> OpenAccVoucheNo { get; set; }
        public Nullable<int> OpenInvAdjNo { get; set; }
    }
}
