//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_COST_CENTER
    {
        public int COMP_CODE { get; set; }
        public string CC_CODE { get; set; }
        public string CC_DESCA { get; set; }
        public string CC_PARENT { get; set; }
        public short CC_LEVEL { get; set; }
        public string CC_LOCATION { get; set; }
        public Nullable<decimal> CC_TARGET { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<bool> PAYROLL_UPDATE { get; set; }
        public Nullable<bool> LEAF { get; set; }
        public string CC_DESCE { get; set; }
    }
}
