//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_REGION_BRANCH
    {
        public int COMP_CODE { get; set; }
        public int RGN_CODE { get; set; }
        public int BRA_CODE { get; set; }
    }
}
