//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_RoleModule
    {
        public int RoleId { get; set; }
        public string SYSTEM_CODE { get; set; }
        public string SUB_SYSTEM_CODE { get; set; }
        public string MODULE_CODE { get; set; }
        public Nullable<bool> EXECUTE { get; set; }
        public Nullable<bool> CREATE { get; set; }
        public Nullable<bool> EDIT { get; set; }
        public Nullable<bool> DELETE { get; set; }
        public Nullable<bool> PRINT { get; set; }
        public Nullable<bool> VIEW { get; set; }
        public Nullable<bool> CUSTOM1 { get; set; }
        public Nullable<bool> CUSTOM2 { get; set; }
        public Nullable<bool> CUSTOM3 { get; set; }
        public Nullable<bool> CUSTOM4 { get; set; }
        public Nullable<bool> CUSTOM5 { get; set; }
        public Nullable<bool> CUSTOM6 { get; set; }
        public Nullable<bool> CUSTOM7 { get; set; }
        public Nullable<bool> CUSTOM8 { get; set; }
        public Nullable<bool> CUSTOM9 { get; set; }
        public Nullable<bool> ViewImages { get; set; }
        public Nullable<bool> EditImages { get; set; }
    }
}
