//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_SearchForm
    {
        public string SearchFormCode { get; set; }
        public string ReturnDataPropertyName { get; set; }
        public string Description { get; set; }
        public string SerachFormTitle { get; set; }
        public bool IsFullScreen { get; set; }
        public int Left { get; set; }
        public int Top { get; set; }
        public int Height { get; set; }
        public int Width { get; set; }
        public int PageSize { get; set; }
        public string DataSourceName { get; set; }
        public int SearchInterval { get; set; }
        public string SerachFormTitleA { get; set; }
    }
}
