//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_STORE
    {
        public int StoreId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> COMP_CODE { get; set; }
        public Nullable<int> BRA_CODE { get; set; }
        public Nullable<int> STORE_CODE { get; set; }
        public string DescA { get; set; }
        public string DescL { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string StockAccCode { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Fax { get; set; }
        public string Address { get; set; }
        public Nullable<byte> STORE_TYPE { get; set; }
        public Nullable<byte> TYPE_CODE { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    }
}
