//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_SUB_SYSTEMS
    {
        public string SYSTEM_CODE { get; set; }
        public string SUB_SYSTEM_CODE { get; set; }
        public string SUB_SYSTEM_DESCA { get; set; }
        public string SUB_SYSTEM_DESCE { get; set; }
        public string ICON_PATH { get; set; }
        public string APPNAME { get; set; }
        public string APPVERSION { get; set; }
        public string AppApiUrl { get; set; }
    }
}
