//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_USER_LOG
    {
        public string USER_CODE { get; set; }
        public string SYSTEM_CODE { get; set; }
        public short SYSTEM_YEAR { get; set; }
        public string MODULE_CODE { get; set; }
        public int COMP_CODE { get; set; }
        public System.DateTime LOG_DATE { get; set; }
    }
}
