//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_USER_MODULE
    {
        public int UserModuleId { get; set; }
        public int UserId { get; set; }
        public string ModuleCode { get; set; }
        public string ModuleDescA { get; set; }
        public bool CanOpen { get; set; }
        public bool CanCreate { get; set; }
        public bool CanEdit { get; set; }
        public bool CanDelete { get; set; }
        public bool CanPrint { get; set; }
        public bool CanPreView { get; set; }
        public bool CanPost { get; set; }
        public Nullable<byte> PrintCopies { get; set; }
        public Nullable<bool> PrintWithSave { get; set; }
        public string DefaultReport { get; set; }
        public bool CUSTOM1 { get; set; }
    }
}
