//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_UserScreenFields
    {
        public int ScreenFieldId { get; set; }
        public Nullable<int> UserModuleId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> UserGroupId { get; set; }
        public string FieldName { get; set; }
        public string AuthDesc { get; set; }
        public Nullable<bool> Authinticated { get; set; }
        public Nullable<int> AuthenticatedBy { get; set; }
    }
}
