//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_VatNature
    {
        public int VatNatID { get; set; }
        public string VatNatureCode { get; set; }
        public string VatNatureDescA { get; set; }
        public string VatNatureDescE { get; set; }
        public Nullable<decimal> VatPrc { get; set; }
    }
}
