//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class GQ_GetUserBarnchAccess
    {
        public string USER_CODE { get; set; }
        public int COMP_CODE { get; set; }
        public int BRA_CODE { get; set; }
        public string BRA_DESCL { get; set; }
        public string BRA_DESCE { get; set; }
        public string BRA_DESC { get; set; }
        public bool EXECUTE { get; set; }
        public bool CREATE { get; set; }
        public bool EDIT { get; set; }
        public bool DELETE { get; set; }
        public bool PRINT { get; set; }
    }
}
