//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class GQ_GetUserModule
    {
        public string USER_CODE { get; set; }
        public string SYSTEM_CODE { get; set; }
        public string SUB_SYSTEM_CODE { get; set; }
        public string MODULE_CODE { get; set; }
        public bool EXECUTE { get; set; }
        public bool CREATE { get; set; }
        public bool EDIT { get; set; }
        public bool DELETE { get; set; }
        public bool PRINT { get; set; }
        public bool VIEW { get; set; }
        public bool CUSTOM1 { get; set; }
        public bool CUSTOM2 { get; set; }
        public bool CUSTOM3 { get; set; }
        public Nullable<bool> CUSTOM4 { get; set; }
        public Nullable<bool> CUSTOM5 { get; set; }
        public Nullable<bool> CUSTOM6 { get; set; }
        public Nullable<bool> CUSTOM7 { get; set; }
        public Nullable<bool> CUSTOM8 { get; set; }
        public Nullable<bool> CUSTOM9 { get; set; }
        public Nullable<bool> ViewImages { get; set; }
        public Nullable<bool> EditImages { get; set; }
        public string MENU_NO { get; set; }
        public string MODULE_DESCE { get; set; }
        public string MODULE_DESCA { get; set; }
        public bool M_CREATE { get; set; }
        public bool M_EDIT { get; set; }
        public bool M_DELETE { get; set; }
        public bool M_VIEW { get; set; }
        public bool M_PRINT { get; set; }
        public bool M_CUSTOM1 { get; set; }
        public bool M_CUSTOM2 { get; set; }
        public bool M_CUSTOM3 { get; set; }
        public Nullable<bool> M_CUSTOM4 { get; set; }
        public Nullable<bool> M_CUSTOM5 { get; set; }
        public Nullable<bool> M_CUSTOM6 { get; set; }
        public Nullable<bool> M_CUSTOM7 { get; set; }
        public Nullable<bool> M_CUSTOM8 { get; set; }
        public Nullable<bool> M_CUSTOM9 { get; set; }
        public string CUSTOM1_DESC { get; set; }
        public string CUSTOM2_DESC { get; set; }
        public string CUSTOM3_DESC { get; set; }
        public string CUSTOM4_DESC { get; set; }
        public string CUSTOM5_DESC { get; set; }
        public string CUSTOM6_DESC { get; set; }
        public string CUSTOM7_DESC { get; set; }
        public string CUSTOM8_DESC { get; set; }
        public string CUSTOM9_DESC { get; set; }
        public Nullable<bool> AVAILABLE { get; set; }
        public Nullable<bool> M_images_enabled { get; set; }
    }
}
