//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class GQ_ReportWebSetting
    {
        public int ReportSettingID { get; set; }
        public string SystemCode { get; set; }
        public string SubSystemCode { get; set; }
        public string ReportID { get; set; }
        public string NameA { get; set; }
        public string NameE { get; set; }
        public Nullable<int> COMP_CODE { get; set; }
        public Nullable<int> BRA_Code { get; set; }
        public string USER_CODE { get; set; }
        public string ReportDesignNameEn { get; set; }
        public string ReportDesignNameAr { get; set; }
        public string ReportDataSouce { get; set; }
        public Nullable<int> RightMarginMM { get; set; }
        public Nullable<int> LeftMarginMM { get; set; }
        public Nullable<int> TopMarginMM { get; set; }
        public Nullable<int> BottomMarginMM { get; set; }
        public Nullable<bool> IsLandScape { get; set; }
        public string PageSize { get; set; }
        public Nullable<decimal> PageHightCM { get; set; }
        public Nullable<decimal> PageWidthCM { get; set; }
        public string PrinterName { get; set; }
        public Nullable<byte> OutputTypeNo { get; set; }
        public string OutputType { get; set; }
    }
}
