//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIJRA_CONVERT
    {
        public short HYEAR { get; set; }
        public System.DateTime START_DATE { get; set; }
        public string MONTHSTMAP { get; set; }
    }
}
