//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_AttendDocDetails
    {
        public int AttendDocDetailsId { get; set; }
        public Nullable<int> AttendDocId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<System.DateTime> AttendDate { get; set; }
        public Nullable<System.DateTime> DismissDate { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public Nullable<System.DateTime> FirstShftFrom { get; set; }
        public Nullable<System.DateTime> FirstShftTo { get; set; }
        public Nullable<System.DateTime> SecondShftFrom { get; set; }
        public Nullable<System.DateTime> SecondShftTo { get; set; }
        public Nullable<System.DateTime> ThirdShftFrom { get; set; }
        public Nullable<System.DateTime> ThirdShftTo { get; set; }
        public Nullable<decimal> AttenDelayByMinutes { get; set; }
        public Nullable<decimal> AttenDelayByHours { get; set; }
        public Nullable<decimal> AttenDelayByDays { get; set; }
        public Nullable<decimal> EarlyAttendByMinutes { get; set; }
        public Nullable<decimal> EarlyAttendByHours { get; set; }
        public Nullable<decimal> EarlyAttendByDays { get; set; }
        public Nullable<decimal> EarlyLeaveByMinutes { get; set; }
        public Nullable<decimal> EarlyLeaveByHours { get; set; }
        public Nullable<decimal> EarlyLeaveByDays { get; set; }
        public Nullable<decimal> OverTimeByMinutes { get; set; }
        public Nullable<decimal> OverTimeByHours { get; set; }
        public Nullable<decimal> OverTimeByDays { get; set; }
        public Nullable<decimal> NetTimeByMinutes { get; set; }
        public Nullable<decimal> NetTimeByHours { get; set; }
        public Nullable<decimal> NetTimeByDays { get; set; }
        public Nullable<int> LeavPermisionId1 { get; set; }
        public Nullable<int> LeavPermisionId2 { get; set; }
        public Nullable<int> LeavPermisionId3 { get; set; }
        public Nullable<int> LeavPermisionId4 { get; set; }
        public Nullable<int> LeavPermisionId5 { get; set; }
        public Nullable<int> LeavPermisionId6 { get; set; }
    }
}
