//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_AttendElementTrans
    {
        public int ElementTransId { get; set; }
        public string TableCode { get; set; }
        public Nullable<int> TableId { get; set; }
        public Nullable<int> AttendElementId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<int> FinancialIntervalsId { get; set; }
        public Nullable<int> PeriodTableId { get; set; }
        public Nullable<int> PeriodTablDetailId { get; set; }
        public Nullable<bool> IsPlus { get; set; }
        public Nullable<System.DateTime> OriginalDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<byte> TimeUnit { get; set; }
        public Nullable<decimal> ElementValue { get; set; }
    }
}
