//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_AttendDocFactElements
    {
        public int FactAttendId { get; set; }
        public Nullable<int> AttendDocId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public Nullable<decimal> TotalWorkDaysPeriod { get; set; }
        public Nullable<decimal> TotalWorkHoursPeriod { get; set; }
        public Nullable<decimal> WorkDayShow { get; set; }
        public Nullable<decimal> WorkDayNoShow { get; set; }
        public Nullable<decimal> Shift1Show { get; set; }
        public Nullable<decimal> Shift1NoShow { get; set; }
        public Nullable<decimal> Shift2Show { get; set; }
        public Nullable<decimal> Shift2NoShow { get; set; }
        public Nullable<decimal> Shift3Show { get; set; }
        public Nullable<decimal> Shift3NoShow { get; set; }
        public Nullable<decimal> LateArrivalMinutes { get; set; }
        public Nullable<decimal> LateArrivalHours { get; set; }
        public Nullable<decimal> LateArrivalDays { get; set; }
        public Nullable<byte> LateArrivalCount { get; set; }
        public Nullable<decimal> EarlyLeaveMinutes { get; set; }
        public Nullable<decimal> EarlyLeaveHours { get; set; }
        public Nullable<decimal> EarlyLeaveDays { get; set; }
        public Nullable<byte> EarlyLeaveCount { get; set; }
        public Nullable<decimal> EarlyAttendMinutes { get; set; }
        public Nullable<decimal> EarlyAttendHours { get; set; }
        public Nullable<decimal> EarlyAttendDays { get; set; }
        public Nullable<byte> EarlyAttendCount { get; set; }
        public Nullable<decimal> WorkdayOvertimeMinutes { get; set; }
        public Nullable<decimal> WorkdayOvertimeHours { get; set; }
        public Nullable<decimal> WorkdayOvertimeDays { get; set; }
        public Nullable<byte> WorkdayOvertimeCount { get; set; }
        public Nullable<decimal> VacationOvertimeMinutes { get; set; }
        public Nullable<decimal> VacationOvertimeHours { get; set; }
        public Nullable<decimal> VacationOvertimeDays { get; set; }
        public Nullable<byte> VacationOvertimeCount { get; set; }
        public Nullable<decimal> WeekendOvertimeMinutes { get; set; }
        public Nullable<decimal> WeekendOvertimeHours { get; set; }
        public Nullable<decimal> WeekendOvertimeDays { get; set; }
        public Nullable<byte> WeekendOvertimeCount { get; set; }
        public Nullable<int> WeekEndWorkShow { get; set; }
        public Nullable<decimal> WeekEndWorkMinutes { get; set; }
        public Nullable<decimal> WeekEndWorkHours { get; set; }
        public Nullable<decimal> WeekEndWorkDays { get; set; }
        public Nullable<int> VacationWorkShow { get; set; }
        public Nullable<decimal> VacationWorkMinutes { get; set; }
        public Nullable<decimal> VacationWorkHours { get; set; }
        public Nullable<decimal> VacationWorkDays { get; set; }
    }
}
