//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_EmpMovePromotDetail
    {
        public int EmpMoveDetailId { get; set; }
        public Nullable<int> EmpMoveId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<int> SalaryTypId { get; set; }
        public Nullable<decimal> OldSalaryValu { get; set; }
        public Nullable<decimal> SalaryValu { get; set; }
    }
}
