//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_EmpVacationsDetails
    {
        public int EmpVacDetailId { get; set; }
        public Nullable<int> EmpVacId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<byte> OldAnnualVacs { get; set; }
        public Nullable<byte> OldReservedVacs { get; set; }
        public Nullable<byte> OldAnnualBalance { get; set; }
        public Nullable<byte> OldReservedVacsBalance { get; set; }
        public Nullable<byte> AnnualVacs { get; set; }
        public Nullable<byte> ReservedVacs { get; set; }
        public Nullable<byte> AnnualBalance { get; set; }
        public Nullable<byte> ReservedVacsBalance { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string Remarks { get; set; }
    }
}
