//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_Employees
    {
        public int EmpId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<int> DepartMentId { get; set; }
        public Nullable<int> HREmpGroupId { get; set; }
        public Nullable<int> PeriodTableId { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> CostCenterId1 { get; set; }
        public Nullable<int> CostCenterId2 { get; set; }
        public string EmpCode { get; set; }
        public string DeviceEmpCode { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string Qualification { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<byte> MaritalStatus { get; set; }
        public Nullable<byte> KidsNo { get; set; }
        public Nullable<byte> Religion { get; set; }
        public Nullable<byte> Nationality { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Remarks { get; set; }
        public string IDNo { get; set; }
        public Nullable<System.DateTime> IDIssueDate { get; set; }
        public Nullable<System.DateTime> IDExpiryDate { get; set; }
        public string PassportNo { get; set; }
        public Nullable<System.DateTime> PassportIssueDate { get; set; }
        public Nullable<System.DateTime> PassportExpiryDate { get; set; }
        public string Car { get; set; }
        public string DrivingLicense { get; set; }
        public Nullable<System.DateTime> DrivingIssueDate { get; set; }
        public Nullable<System.DateTime> DrivingExpiryDate { get; set; }
        public Nullable<System.DateTime> DrivingRenewalDate { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public string Email { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public Nullable<byte> AnnualVacs { get; set; }
        public Nullable<byte> ReservedVacs { get; set; }
        public Nullable<System.DateTime> LastVacsUpdate { get; set; }
        public Nullable<byte> AnnualVacsBalance { get; set; }
        public Nullable<byte> ReservedVacsBalance { get; set; }
        public Nullable<byte> MaxVacsBalance { get; set; }
        public Nullable<bool> ContractType { get; set; }
        public Nullable<bool> Attendance { get; set; }
        public Nullable<System.DateTime> ContractSrtDate { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public Nullable<System.DateTime> WorkStartDate { get; set; }
        public string SocialSecurityID { get; set; }
        public string HealthInsID { get; set; }
        public Nullable<System.DateTime> HealthInsEndDate { get; set; }
        public string syndicate { get; set; }
        public string syndicateID { get; set; }
        public Nullable<byte> MilitaryService { get; set; }
        public Nullable<decimal> HourlyCostRate { get; set; }
        public Nullable<bool> IsTechnician { get; set; }
        public Nullable<bool> IsSales { get; set; }
        public Nullable<bool> IsMoneyCollector { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public byte[] EmpImage { get; set; }
        public Nullable<bool> IssueSalary { get; set; }
        public Nullable<bool> DistributeSalary { get; set; }
        public Nullable<bool> AutosalaryIssue { get; set; }
        public string BankName { get; set; }
        public string BankAccNo { get; set; }
        public Nullable<decimal> DailyCost { get; set; }
        public Nullable<decimal> HourlyCost { get; set; }
        public Nullable<decimal> TotalDailyCost { get; set; }
        public Nullable<decimal> TotalHourlyCost { get; set; }
        public Nullable<decimal> CommisionPercent { get; set; }
        public Nullable<decimal> CommisionCollectionPerc { get; set; }
        public Nullable<bool> IsCommissionAfterDisc { get; set; }
        public string TaxRefNo { get; set; }
        public string EtaxCustType { get; set; }
    }
}
