//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_Jobs
    {
        public int JobId { get; set; }
        public Nullable<int> DepartMentId { get; set; }
        public string JCode { get; set; }
        public string JName1 { get; set; }
        public string JName2 { get; set; }
        public string JDesc { get; set; }
        public string JResponsibilities { get; set; }
        public string JDuties { get; set; }
        public string JQualifications { get; set; }
        public string Remarks { get; set; }
        public string Add1 { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<decimal> StandardMonthlyWage { get; set; }
        public Nullable<byte> StandardHolyDays { get; set; }
        public Nullable<decimal> StandardDailyWage { get; set; }
        public Nullable<decimal> StandardDailyWorkHours { get; set; }
        public Nullable<decimal> StandardHourlyWage { get; set; }
        public Nullable<int> NumberAvailable { get; set; }
    }
}
