//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_MobileSetting
    {
        public int HrMobSetId { get; set; }
        public Nullable<int> DefPermReqBookId { get; set; }
        public Nullable<int> DefVacReqBookId { get; set; }
        public Nullable<int> DefLoanReqBookId { get; set; }
        public Nullable<int> TermId { get; set; }
    }
}
