//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_PeriodTableDetail
    {
        public int PeriodTablDetailId { get; set; }
        public Nullable<int> PeriodTableId { get; set; }
        public string SubPeriodCode { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public Nullable<System.DateTime> PeriodStrtDate { get; set; }
        public Nullable<System.DateTime> PeriodEndDate { get; set; }
        public Nullable<System.DateTime> PayDayDate { get; set; }
        public Nullable<decimal> TotalWorkDays { get; set; }
        public Nullable<decimal> TotalWorkHours { get; set; }
        public Nullable<decimal> TotalVacsDays { get; set; }
        public Nullable<decimal> TotalVacsHours { get; set; }
    }
}
