//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_SalaryIssueDistribution
    {
        public int SalaryIssuDistId { get; set; }
        public Nullable<int> SalaryIssuDocId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> CostCenterId { get; set; }
        public Nullable<decimal> SalaryHours { get; set; }
        public Nullable<decimal> SalaryDays { get; set; }
        public Nullable<decimal> SalaryPercent { get; set; }
        public Nullable<decimal> ValueShare { get; set; }
    }
}
