//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_SalaryTypes
    {
        public int SalaryTypId { get; set; }
        public Nullable<int> AttendElementId { get; set; }
        public Nullable<byte> SalaryCalcMethod { get; set; }
        public string SalaryCode { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public Nullable<decimal> SalaryValu { get; set; }
        public Nullable<byte> UseType { get; set; }
        public Nullable<byte> AffectType { get; set; }
        public Nullable<byte> ImplementScale { get; set; }
        public Nullable<int> ParentRelation { get; set; }
        public Nullable<decimal> Multiply { get; set; }
        public Nullable<decimal> Devide { get; set; }
        public Nullable<byte> Approximation { get; set; }
        public Nullable<decimal> MaximumVal { get; set; }
        public Nullable<decimal> MinimumVal { get; set; }
        public Nullable<byte> DebitAccFilter { get; set; }
        public Nullable<int> DebitAccId { get; set; }
        public Nullable<byte> CreditAccFilter { get; set; }
        public Nullable<int> CreditAccId { get; set; }
        public Nullable<byte> DebitCostCenterFilter { get; set; }
        public Nullable<int> DebitCostCenterId { get; set; }
        public Nullable<byte> CreditCostCenterFilter { get; set; }
        public Nullable<int> CreditCostCenterId { get; set; }
        public Nullable<bool> LargerThanZero { get; set; }
        public Nullable<bool> CanDelet { get; set; }
        public Nullable<bool> AutoIssue { get; set; }
        public Nullable<bool> CanEdit { get; set; }
        public Nullable<bool> Distributable { get; set; }
        public Nullable<bool> IsBasicsalary { get; set; }
        public Nullable<byte> Indmnity { get; set; }
        public Nullable<byte> Taxation { get; set; }
        public Nullable<byte> SocialSecurity { get; set; }
        public Nullable<decimal> ElementCount { get; set; }
        public string ElementCountDesc { get; set; }
        public Nullable<bool> UseElementOrUnit { get; set; }
        public string Equation { get; set; }
        public Nullable<bool> IsAnnualSegment { get; set; }
        public Nullable<int> AnnualPeriods { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    }
}
