//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_Shifts
    {
        public int ShiftId { get; set; }
        public string ShiftCode { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string Day1Name1 { get; set; }
        public string Day1Name2 { get; set; }
        public string Day2Name1 { get; set; }
        public string Day2Name2 { get; set; }
        public string Day3Name1 { get; set; }
        public string Day3Name2 { get; set; }
        public string Day4Name1 { get; set; }
        public string Day4Name2 { get; set; }
        public string Day5Name1 { get; set; }
        public string Day5Name2 { get; set; }
        public string Day6Name1 { get; set; }
        public string Day6Name2 { get; set; }
        public string Day7Name1 { get; set; }
        public string Day7Name2 { get; set; }
        public Nullable<bool> Day1Type { get; set; }
        public Nullable<bool> Day2Type { get; set; }
        public Nullable<bool> Day3Type { get; set; }
        public Nullable<bool> Day4Type { get; set; }
        public Nullable<bool> Day5Type { get; set; }
        public Nullable<bool> Day6Type { get; set; }
        public Nullable<bool> Day7Type { get; set; }
        public Nullable<System.DateTime> FirstShfDay1tFrom { get; set; }
        public Nullable<System.DateTime> FirstShftDay1To { get; set; }
        public Nullable<System.DateTime> FirstShftDay2From { get; set; }
        public Nullable<System.DateTime> FirstShftDay2To { get; set; }
        public Nullable<System.DateTime> FirstShftDay3From { get; set; }
        public Nullable<System.DateTime> FirstShftDay3To { get; set; }
        public Nullable<System.DateTime> FirstShftDay4From { get; set; }
        public Nullable<System.DateTime> FirstShftDay4To { get; set; }
        public Nullable<System.DateTime> FirstShftDay5From { get; set; }
        public Nullable<System.DateTime> FirstShftDay5To { get; set; }
        public Nullable<System.DateTime> FirstShftDay6From { get; set; }
        public Nullable<System.DateTime> FirstShftDay6To { get; set; }
        public Nullable<System.DateTime> FirstShftDay7From { get; set; }
        public Nullable<System.DateTime> FirstShftDay7To { get; set; }
        public Nullable<System.DateTime> SecondShftDay1From { get; set; }
        public Nullable<System.DateTime> SecondShftDay1To { get; set; }
        public Nullable<System.DateTime> SecondShftDay2From { get; set; }
        public Nullable<System.DateTime> SecondShftDay2To { get; set; }
        public Nullable<System.DateTime> SecondShftDay3From { get; set; }
        public Nullable<System.DateTime> SecondShftDay3To { get; set; }
        public Nullable<System.DateTime> SecondShftDay4From { get; set; }
        public Nullable<System.DateTime> SecondShftDay4To { get; set; }
        public Nullable<System.DateTime> SecondShftDay5From { get; set; }
        public Nullable<System.DateTime> SecondShftDay5To { get; set; }
        public Nullable<System.DateTime> SecondShftDay6From { get; set; }
        public Nullable<System.DateTime> SecondShftDay6To { get; set; }
        public Nullable<System.DateTime> SecondShftDay7From { get; set; }
        public Nullable<System.DateTime> SecondShftDay7To { get; set; }
        public Nullable<System.DateTime> ThirdShftDay1From { get; set; }
        public Nullable<System.DateTime> ThirdShftDay1To { get; set; }
        public Nullable<System.DateTime> ThirdShftDay2From { get; set; }
        public Nullable<System.DateTime> ThirdShftDay2To { get; set; }
        public Nullable<System.DateTime> ThirdShftDay3From { get; set; }
        public Nullable<System.DateTime> ThirdShftDay3To { get; set; }
        public Nullable<System.DateTime> ThirdShftDay4From { get; set; }
        public Nullable<System.DateTime> ThirdShftDay4To { get; set; }
        public Nullable<System.DateTime> ThirdShftDay5From { get; set; }
        public Nullable<System.DateTime> ThirdShftDay5To { get; set; }
        public Nullable<System.DateTime> ThirdShftDay6From { get; set; }
        public Nullable<System.DateTime> ThirdShftDay6To { get; set; }
        public Nullable<System.DateTime> ThirdShftDay7From { get; set; }
        public Nullable<System.DateTime> ThirdShftDay7To { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    }
}
