//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_VW_GetCompStatus
    {
        public int CompCode { get; set; }
        public Nullable<bool> AddAble { get; set; }
        public Nullable<bool> Editable { get; set; }
        public int CompStatus { get; set; }
        public string LoginMsg { get; set; }
    }
}
