//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InvEntities : DbContext
    {
        public InvEntities()
            : base("name=InvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cal_AccountChart> Cal_AccountChart { get; set; }
        public virtual DbSet<G_AlertControl> G_AlertControl { get; set; }
        public virtual DbSet<G_AlertLog> G_AlertLog { get; set; }
        public virtual DbSet<G_AlertType> G_AlertType { get; set; }
        public virtual DbSet<G_BRANCH> G_BRANCH { get; set; }
        public virtual DbSet<G_Codes> G_Codes { get; set; }
        public virtual DbSet<G_COMPANY> G_COMPANY { get; set; }
        public virtual DbSet<G_CONTROL> G_CONTROL { get; set; }
        public virtual DbSet<G_COST_CENTER> G_COST_CENTER { get; set; }
        public virtual DbSet<G_Currency> G_Currency { get; set; }
        public virtual DbSet<G_ModuleHelp> G_ModuleHelp { get; set; }
        public virtual DbSet<G_MODULES> G_MODULES { get; set; }
        public virtual DbSet<G_NotificationCompany> G_NotificationCompany { get; set; }
        public virtual DbSet<G_PaperSize> G_PaperSize { get; set; }
        public virtual DbSet<G_PrintLog> G_PrintLog { get; set; }
        public virtual DbSet<G_REGION> G_REGION { get; set; }
        public virtual DbSet<G_REGION_BRANCH> G_REGION_BRANCH { get; set; }
        public virtual DbSet<G_ReportWebSetting> G_ReportWebSetting { get; set; }
        public virtual DbSet<G_Role> G_Role { get; set; }
        public virtual DbSet<G_RoleModule> G_RoleModule { get; set; }
        public virtual DbSet<G_RoleUsers> G_RoleUsers { get; set; }
        public virtual DbSet<G_SUB_SYSTEMS> G_SUB_SYSTEMS { get; set; }
        public virtual DbSet<G_SYSTEM> G_SYSTEM { get; set; }
        public virtual DbSet<G_TransCounter> G_TransCounter { get; set; }
        public virtual DbSet<G_TransCounterSetting> G_TransCounterSetting { get; set; }
        public virtual DbSet<G_USER_BRANCH> G_USER_BRANCH { get; set; }
        public virtual DbSet<G_USER_COMPANY> G_USER_COMPANY { get; set; }
        public virtual DbSet<G_USER_LOG> G_USER_LOG { get; set; }
        public virtual DbSet<G_USER_MODULE> G_USER_MODULE { get; set; }
        public virtual DbSet<G_UserGroups> G_UserGroups { get; set; }
        public virtual DbSet<G_UserRole> G_UserRole { get; set; }
        public virtual DbSet<G_UserRolePermissions> G_UserRolePermissions { get; set; }
        public virtual DbSet<G_UserScreenFields> G_UserScreenFields { get; set; }
        public virtual DbSet<G_VatNature> G_VatNature { get; set; }
        public virtual DbSet<I_Control> I_Control { get; set; }
        public virtual DbSet<MS_ItemAlternatives> MS_ItemAlternatives { get; set; }
        public virtual DbSet<MS_ItemCard> MS_ItemCard { get; set; }
        public virtual DbSet<Ms_ItemCardOffers> Ms_ItemCardOffers { get; set; }
        public virtual DbSet<MS_ItemCategory> MS_ItemCategory { get; set; }
        public virtual DbSet<Ms_ItemCollection> Ms_ItemCollection { get; set; }
        public virtual DbSet<MS_ItemCostHistory> MS_ItemCostHistory { get; set; }
        public virtual DbSet<Ms_ItemPartition> Ms_ItemPartition { get; set; }
        public virtual DbSet<MS_Partition> MS_Partition { get; set; }
        public virtual DbSet<MS_Stores> MS_Stores { get; set; }
        public virtual DbSet<HIJRA_CONVERT> HIJRA_CONVERT { get; set; }
        public virtual DbSet<I_VW_GetCompStatus> I_VW_GetCompStatus { get; set; }
        public virtual DbSet<GQ_GetUserBarnchAccess> GQ_GetUserBarnchAccess { get; set; }
        public virtual DbSet<GQ_GetUserBranch> GQ_GetUserBranch { get; set; }
        public virtual DbSet<GQ_GetUserRole> GQ_GetUserRole { get; set; }
        public virtual DbSet<GQ_GetUsers> GQ_GetUsers { get; set; }
        public virtual DbSet<GQ_ReportWebSetting> GQ_ReportWebSetting { get; set; }
        public virtual DbSet<Cal_AccountUsers> Cal_AccountUsers { get; set; }
        public virtual DbSet<MS_Currency> MS_Currency { get; set; }
        public virtual DbSet<MS_BoxBank> MS_BoxBank { get; set; }
        public virtual DbSet<MS_CurrencyCategory> MS_CurrencyCategory { get; set; }
        public virtual DbSet<Ms_CurrencyCategoryJoin> Ms_CurrencyCategoryJoin { get; set; }
        public virtual DbSet<Cod_AccountCategories> Cod_AccountCategories { get; set; }
        public virtual DbSet<Cod_AccountClassification> Cod_AccountClassification { get; set; }
        public virtual DbSet<Ms_CustomerTypes> Ms_CustomerTypes { get; set; }
        public virtual DbSet<Ms_VendorTypes> Ms_VendorTypes { get; set; }
        public virtual DbSet<Ms_CusromerUsers> Ms_CusromerUsers { get; set; }
        public virtual DbSet<Ms_CustImgs> Ms_CustImgs { get; set; }
        public virtual DbSet<MS_Customer> MS_Customer { get; set; }
        public virtual DbSet<Ms_CustomerBranches> Ms_CustomerBranches { get; set; }
        public virtual DbSet<MS_CustomerCategory> MS_CustomerCategory { get; set; }
        public virtual DbSet<Ms_CustomerContacts> Ms_CustomerContacts { get; set; }
        public virtual DbSet<Asset_AssetAddDoc> Asset_AssetAddDoc { get; set; }
        public virtual DbSet<Asset_AssetAddDocDetail> Asset_AssetAddDocDetail { get; set; }
        public virtual DbSet<Asset_AssetCard> Asset_AssetCard { get; set; }
        public virtual DbSet<Asset_AssetCategory> Asset_AssetCategory { get; set; }
        public virtual DbSet<Asset_AssetContacts> Asset_AssetContacts { get; set; }
        public virtual DbSet<Asset_AssetDeductDoc> Asset_AssetDeductDoc { get; set; }
        public virtual DbSet<Asset_AssetDeductDocDetail> Asset_AssetDeductDocDetail { get; set; }
        public virtual DbSet<Asset_AssetDeliverDoc> Asset_AssetDeliverDoc { get; set; }
        public virtual DbSet<Asset_AssetDeliverDocDetail> Asset_AssetDeliverDocDetail { get; set; }
        public virtual DbSet<Asset_AssetFixDoc> Asset_AssetFixDoc { get; set; }
        public virtual DbSet<Asset_AssetFixDocDetail> Asset_AssetFixDocDetail { get; set; }
        public virtual DbSet<Asset_AssetMoveDoc> Asset_AssetMoveDoc { get; set; }
        public virtual DbSet<Asset_AssetMoveDocDetail> Asset_AssetMoveDocDetail { get; set; }
        public virtual DbSet<Asset_AssetReceiveDoc> Asset_AssetReceiveDoc { get; set; }
        public virtual DbSet<Asset_AssetReceiveDocDetail> Asset_AssetReceiveDocDetail { get; set; }
        public virtual DbSet<Asset_AssetSettingDetails> Asset_AssetSettingDetails { get; set; }
        public virtual DbSet<Asset_AssetSettings> Asset_AssetSettings { get; set; }
        public virtual DbSet<Asset_DepreciationDoc> Asset_DepreciationDoc { get; set; }
        public virtual DbSet<Asset_DepreciationDocDetail> Asset_DepreciationDocDetail { get; set; }
        public virtual DbSet<Asset_Termination> Asset_Termination { get; set; }
        public virtual DbSet<BNk_BankNotice> BNk_BankNotice { get; set; }
        public virtual DbSet<BNK_BankNoticeDetail> BNK_BankNoticeDetail { get; set; }
        public virtual DbSet<Cal_AccChrtDailyAssist> Cal_AccChrtDailyAssist { get; set; }
        public virtual DbSet<Cal_AccountClaasiJoin> Cal_AccountClaasiJoin { get; set; }
        public virtual DbSet<Cal_AccountingFix> Cal_AccountingFix { get; set; }
        public virtual DbSet<Cal_AssetAccounts> Cal_AssetAccounts { get; set; }
        public virtual DbSet<Cal_Budget> Cal_Budget { get; set; }
        public virtual DbSet<Cal_BudgetDetails> Cal_BudgetDetails { get; set; }
        public virtual DbSet<Cal_BusinessPartnerAccounts> Cal_BusinessPartnerAccounts { get; set; }
        public virtual DbSet<Cal_CostCenterAccount> Cal_CostCenterAccount { get; set; }
        public virtual DbSet<Cal_CostCenters> Cal_CostCenters { get; set; }
        public virtual DbSet<Cal_CustAccounts> Cal_CustAccounts { get; set; }
        public virtual DbSet<Cal_EmpAccounts> Cal_EmpAccounts { get; set; }
        public virtual DbSet<Cal_JurnalDetail> Cal_JurnalDetail { get; set; }
        public virtual DbSet<Cal_JurnalEntry> Cal_JurnalEntry { get; set; }
        public virtual DbSet<Cal_PostOrder> Cal_PostOrder { get; set; }
        public virtual DbSet<Cal_QueueOrder> Cal_QueueOrder { get; set; }
        public virtual DbSet<Cal_VendAccounts> Cal_VendAccounts { get; set; }
        public virtual DbSet<Cod_BuildingDegree> Cod_BuildingDegree { get; set; }
        public virtual DbSet<Cod_BuildingExploitation> Cod_BuildingExploitation { get; set; }
        public virtual DbSet<Cod_BuildingFinishingLevel> Cod_BuildingFinishingLevel { get; set; }
        public virtual DbSet<Cod_BuildingInsuranceStatus> Cod_BuildingInsuranceStatus { get; set; }
        public virtual DbSet<Cod_BuildingStatus> Cod_BuildingStatus { get; set; }
        public virtual DbSet<Cod_BuildingTypes> Cod_BuildingTypes { get; set; }
        public virtual DbSet<Cod_BuildOccupTypes> Cod_BuildOccupTypes { get; set; }
        public virtual DbSet<Cod_BuildPermitActiv> Cod_BuildPermitActiv { get; set; }
        public virtual DbSet<Cod_BuildPerspective> Cod_BuildPerspective { get; set; }
        public virtual DbSet<Cod_City> Cod_City { get; set; }
        public virtual DbSet<Cod_Colors> Cod_Colors { get; set; }
        public virtual DbSet<Cod_ContractType> Cod_ContractType { get; set; }
        public virtual DbSet<Cod_Country> Cod_Country { get; set; }
        public virtual DbSet<Cod_DailyAssistance> Cod_DailyAssistance { get; set; }
        public virtual DbSet<Cod_ElectInsurStatus> Cod_ElectInsurStatus { get; set; }
        public virtual DbSet<Cod_Explanations> Cod_Explanations { get; set; }
        public virtual DbSet<Cod_FurnitAndEqupmnts> Cod_FurnitAndEqupmnts { get; set; }
        public virtual DbSet<Cod_InstallmentTemps> Cod_InstallmentTemps { get; set; }
        public virtual DbSet<Cod_InstallmentTempsDetail> Cod_InstallmentTempsDetail { get; set; }
        public virtual DbSet<Cod_InsuranceCases> Cod_InsuranceCases { get; set; }
        public virtual DbSet<Cod_InsurCovTypes> Cod_InsurCovTypes { get; set; }
        public virtual DbSet<Cod_LandPermitActivJoin> Cod_LandPermitActivJoin { get; set; }
        public virtual DbSet<Cod_LandPermtActiv> Cod_LandPermtActiv { get; set; }
        public virtual DbSet<Cod_LandPositions> Cod_LandPositions { get; set; }
        public virtual DbSet<Cod_LandPosJoin> Cod_LandPosJoin { get; set; }
        public virtual DbSet<Cod_LandRetainResJoin> Cod_LandRetainResJoin { get; set; }
        public virtual DbSet<Cod_LandRetainRsons> Cod_LandRetainRsons { get; set; }
        public virtual DbSet<Cod_Lands> Cod_Lands { get; set; }
        public virtual DbSet<Cod_LandStatus> Cod_LandStatus { get; set; }
        public virtual DbSet<Cod_LandTypes> Cod_LandTypes { get; set; }
        public virtual DbSet<Cod_MaintenanceTypes> Cod_MaintenanceTypes { get; set; }
        public virtual DbSet<Cod_NonRenewalReasons> Cod_NonRenewalReasons { get; set; }
        public virtual DbSet<Cod_OperatingOrders> Cod_OperatingOrders { get; set; }
        public virtual DbSet<Cod_OwnershipBonds> Cod_OwnershipBonds { get; set; }
        public virtual DbSet<Cod_PackingSize> Cod_PackingSize { get; set; }
        public virtual DbSet<Cod_Parkings> Cod_Parkings { get; set; }
        public virtual DbSet<Cod_PaymentTerms> Cod_PaymentTerms { get; set; }
        public virtual DbSet<Cod_PaymentTypes> Cod_PaymentTypes { get; set; }
        public virtual DbSet<Cod_PostalCodes> Cod_PostalCodes { get; set; }
        public virtual DbSet<Cod_Region> Cod_Region { get; set; }
        public virtual DbSet<Cod_RentCase> Cod_RentCase { get; set; }
        public virtual DbSet<Cod_SavingFiles> Cod_SavingFiles { get; set; }
        public virtual DbSet<Cod_Services> Cod_Services { get; set; }
        public virtual DbSet<Cod_Shelves> Cod_Shelves { get; set; }
        public virtual DbSet<Cod_SubRegion> Cod_SubRegion { get; set; }
        public virtual DbSet<Cod_TaskTypes> Cod_TaskTypes { get; set; }
        public virtual DbSet<Cod_TrmsModifiRsons> Cod_TrmsModifiRsons { get; set; }
        public virtual DbSet<Cod_UnitDegree> Cod_UnitDegree { get; set; }
        public virtual DbSet<Cod_UnitExploitation> Cod_UnitExploitation { get; set; }
        public virtual DbSet<Cod_UnitFinishingLevel> Cod_UnitFinishingLevel { get; set; }
        public virtual DbSet<Cod_UnitInsuranceStatus> Cod_UnitInsuranceStatus { get; set; }
        public virtual DbSet<Cod_UnitOccupancyTypes> Cod_UnitOccupancyTypes { get; set; }
        public virtual DbSet<Cod_UnitPermittedActivity> Cod_UnitPermittedActivity { get; set; }
        public virtual DbSet<Cod_UnitPerspective> Cod_UnitPerspective { get; set; }
        public virtual DbSet<Cod_UnitServices> Cod_UnitServices { get; set; }
        public virtual DbSet<Cod_UnitStatus> Cod_UnitStatus { get; set; }
        public virtual DbSet<Cod_UnitTypes> Cod_UnitTypes { get; set; }
        public virtual DbSet<Cod_UntMntanItmBylndownrTnant> Cod_UntMntanItmBylndownrTnant { get; set; }
        public virtual DbSet<Code_SubUnitTypes> Code_SubUnitTypes { get; set; }
        public virtual DbSet<Contr_InstallMent> Contr_InstallMent { get; set; }
        public virtual DbSet<Contr_InstallMentDetail> Contr_InstallMentDetail { get; set; }
        public virtual DbSet<CRM_Leads> CRM_Leads { get; set; }
        public virtual DbSet<CRM_LeadsMembers> CRM_LeadsMembers { get; set; }
        public virtual DbSet<CRM_LeadsMembersDetails> CRM_LeadsMembersDetails { get; set; }
        public virtual DbSet<CRM_LeadsMembersJoin> CRM_LeadsMembersJoin { get; set; }
        public virtual DbSet<CRM_LeadTypes> CRM_LeadTypes { get; set; }
        public virtual DbSet<CRM_MarketChannels> CRM_MarketChannels { get; set; }
        public virtual DbSet<CRM_SalesPlan> CRM_SalesPlan { get; set; }
        public virtual DbSet<CRM_SalesPlanDetail> CRM_SalesPlanDetail { get; set; }
        public virtual DbSet<CRM_Survey> CRM_Survey { get; set; }
        public virtual DbSet<CRM_SurveyMemberJoin> CRM_SurveyMemberJoin { get; set; }
        public virtual DbSet<CRM_TeamMembers> CRM_TeamMembers { get; set; }
        public virtual DbSet<CRM_Teams> CRM_Teams { get; set; }
        public virtual DbSet<CRM_Visits> CRM_Visits { get; set; }
        public virtual DbSet<CRM_VisitSurveys> CRM_VisitSurveys { get; set; }
        public virtual DbSet<CRM_VisitTypes> CRM_VisitTypes { get; set; }
        public virtual DbSet<G_Nationality> G_Nationality { get; set; }
        public virtual DbSet<G_News> G_News { get; set; }
        public virtual DbSet<G_Noteifications> G_Noteifications { get; set; }
        public virtual DbSet<G_STORE> G_STORE { get; set; }
        public virtual DbSet<Hr_ActivityDetailElements> Hr_ActivityDetailElements { get; set; }
        public virtual DbSet<Hr_AttendanceDoc> Hr_AttendanceDoc { get; set; }
        public virtual DbSet<Hr_AttendanceElements> Hr_AttendanceElements { get; set; }
        public virtual DbSet<Hr_AttendDocDetails> Hr_AttendDocDetails { get; set; }
        public virtual DbSet<Hr_AttendDocFactElements> Hr_AttendDocFactElements { get; set; }
        public virtual DbSet<Hr_AttendElementTrans> Hr_AttendElementTrans { get; set; }
        public virtual DbSet<Hr_Departments> Hr_Departments { get; set; }
        public virtual DbSet<Hr_Education> Hr_Education { get; set; }
        public virtual DbSet<Hr_EmpActivity> Hr_EmpActivity { get; set; }
        public virtual DbSet<Hr_EmpActivityDetail> Hr_EmpActivityDetail { get; set; }
        public virtual DbSet<Hr_EmpDocTypes> Hr_EmpDocTypes { get; set; }
        public virtual DbSet<Hr_EmpDocuments> Hr_EmpDocuments { get; set; }
        public virtual DbSet<Hr_EmpElementPeriodBalance> Hr_EmpElementPeriodBalance { get; set; }
        public virtual DbSet<Hr_EmpGroups> Hr_EmpGroups { get; set; }
        public virtual DbSet<Hr_EmpLoanRequest> Hr_EmpLoanRequest { get; set; }
        public virtual DbSet<Hr_EmpLoans> Hr_EmpLoans { get; set; }
        public virtual DbSet<Hr_EmpMovePromotDetail> Hr_EmpMovePromotDetail { get; set; }
        public virtual DbSet<Hr_EmpMovePromotion> Hr_EmpMovePromotion { get; set; }
        public virtual DbSet<Hr_EmpSalaryDistribution> Hr_EmpSalaryDistribution { get; set; }
        public virtual DbSet<Hr_EmpSalaryTypes> Hr_EmpSalaryTypes { get; set; }
        public virtual DbSet<Hr_EmpsSalaryTemp> Hr_EmpsSalaryTemp { get; set; }
        public virtual DbSet<Hr_EmpVacation> Hr_EmpVacation { get; set; }
        public virtual DbSet<Hr_EmpVacationsDetails> Hr_EmpVacationsDetails { get; set; }
        public virtual DbSet<Hr_Jobs> Hr_Jobs { get; set; }
        public virtual DbSet<Hr_KPIS> Hr_KPIS { get; set; }
        public virtual DbSet<Hr_LeavePermision> Hr_LeavePermision { get; set; }
        public virtual DbSet<Hr_LeavPermissionRequest> Hr_LeavPermissionRequest { get; set; }
        public virtual DbSet<HR_MobileSetting> HR_MobileSetting { get; set; }
        public virtual DbSet<Hr_PeriodsTables> Hr_PeriodsTables { get; set; }
        public virtual DbSet<Hr_PeriodTableDetail> Hr_PeriodTableDetail { get; set; }
        public virtual DbSet<Hr_PeriodTablePolicy> Hr_PeriodTablePolicy { get; set; }
        public virtual DbSet<Hr_PeriodTableVacations> Hr_PeriodTableVacations { get; set; }
        public virtual DbSet<Hr_RewardAndPenalty> Hr_RewardAndPenalty { get; set; }
        public virtual DbSet<Hr_SalaryCalcMethod> Hr_SalaryCalcMethod { get; set; }
        public virtual DbSet<Hr_SalaryIssueDetails> Hr_SalaryIssueDetails { get; set; }
        public virtual DbSet<Hr_SalaryIssueDistribution> Hr_SalaryIssueDistribution { get; set; }
        public virtual DbSet<Hr_SalaryIssueDoc> Hr_SalaryIssueDoc { get; set; }
        public virtual DbSet<Hr_SalaryTypes> Hr_SalaryTypes { get; set; }
        public virtual DbSet<Hr_Segments> Hr_Segments { get; set; }
        public virtual DbSet<Hr_Shifts> Hr_Shifts { get; set; }
        public virtual DbSet<Hr_Termination> Hr_Termination { get; set; }
        public virtual DbSet<Hr_VacationDoc> Hr_VacationDoc { get; set; }
        public virtual DbSet<Hr_VacationEdit> Hr_VacationEdit { get; set; }
        public virtual DbSet<Hr_VacationRequest> Hr_VacationRequest { get; set; }
        public virtual DbSet<La_Lands> La_Lands { get; set; }
        public virtual DbSet<La_PropSerial> La_PropSerial { get; set; }
        public virtual DbSet<Ms_AdjustMents> Ms_AdjustMents { get; set; }
        public virtual DbSet<Ms_Attachments> Ms_Attachments { get; set; }
        public virtual DbSet<Ms_BankAccount> Ms_BankAccount { get; set; }
        public virtual DbSet<MS_BoxCurrency> MS_BoxCurrency { get; set; }
        public virtual DbSet<MS_BoxTransferDetail> MS_BoxTransferDetail { get; set; }
        public virtual DbSet<MS_BoxTransferNote> MS_BoxTransferNote { get; set; }
        public virtual DbSet<Ms_BoxUsers> Ms_BoxUsers { get; set; }
        public virtual DbSet<Ms_BusinessPartnerCategory> Ms_BusinessPartnerCategory { get; set; }
        public virtual DbSet<Ms_BusinessPartners> Ms_BusinessPartners { get; set; }
        public virtual DbSet<Ms_BusinessPartnerType> Ms_BusinessPartnerType { get; set; }
        public virtual DbSet<MS_CashTransactionDetail> MS_CashTransactionDetail { get; set; }
        public virtual DbSet<Ms_CheqBooks> Ms_CheqBooks { get; set; }
        public virtual DbSet<Ms_ChequesOpenning> Ms_ChequesOpenning { get; set; }
        public virtual DbSet<Ms_ChequeTransfer> Ms_ChequeTransfer { get; set; }
        public virtual DbSet<Ms_ChequeTransferDetail> Ms_ChequeTransferDetail { get; set; }
        public virtual DbSet<Ms_Commission> Ms_Commission { get; set; }
        public virtual DbSet<MS_Company> MS_Company { get; set; }
        public virtual DbSet<Ms_CurrencyDailyRateChanges> Ms_CurrencyDailyRateChanges { get; set; }
        public virtual DbSet<Ms_CurrencyRate> Ms_CurrencyRate { get; set; }
        public virtual DbSet<Ms_DeliverItemCard> Ms_DeliverItemCard { get; set; }
        public virtual DbSet<Ms_DeliverSalesInvoice> Ms_DeliverSalesInvoice { get; set; }
        public virtual DbSet<Ms_DeliverSalesInvoiceExpenses> Ms_DeliverSalesInvoiceExpenses { get; set; }
        public virtual DbSet<Ms_DeliverSalesInvoiceMultiAccounts> Ms_DeliverSalesInvoiceMultiAccounts { get; set; }
        public virtual DbSet<Ms_Description> Ms_Description { get; set; }
        public virtual DbSet<MS_Expenses> MS_Expenses { get; set; }
        public virtual DbSet<Ms_ItemCardVendors> Ms_ItemCardVendors { get; set; }
        public virtual DbSet<MS_ItemSerials> MS_ItemSerials { get; set; }
        public virtual DbSet<MS_ItemSerialsTransactions> MS_ItemSerialsTransactions { get; set; }
        public virtual DbSet<Ms_ItemShortage> Ms_ItemShortage { get; set; }
        public virtual DbSet<Ms_ItemStartQty> Ms_ItemStartQty { get; set; }
        public virtual DbSet<Ms_ItemStockAdjustment> Ms_ItemStockAdjustment { get; set; }
        public virtual DbSet<Ms_ItemStockAdjustmentDetail> Ms_ItemStockAdjustmentDetail { get; set; }
        public virtual DbSet<Ms_ItemUnit> Ms_ItemUnit { get; set; }
        public virtual DbSet<Ms_ItemUnitPackingJoin> Ms_ItemUnitPackingJoin { get; set; }
        public virtual DbSet<MS_ItemVendors> MS_ItemVendors { get; set; }
        public virtual DbSet<Ms_KeeperBank> Ms_KeeperBank { get; set; }
        public virtual DbSet<Ms_KeeperBankDetail> Ms_KeeperBankDetail { get; set; }
        public virtual DbSet<Ms_LetterOfGuarantee> Ms_LetterOfGuarantee { get; set; }
        public virtual DbSet<Ms_LetterOfGuaranteeCategory> Ms_LetterOfGuaranteeCategory { get; set; }
        public virtual DbSet<Ms_LetterOfGuaranteeStatus> Ms_LetterOfGuaranteeStatus { get; set; }
        public virtual DbSet<Ms_LetterOfGuaranteeTrans> Ms_LetterOfGuaranteeTrans { get; set; }
        public virtual DbSet<Ms_LetterOfGuaranteeTypes> Ms_LetterOfGuaranteeTypes { get; set; }
        public virtual DbSet<MS_LotNumberConfiguration> MS_LotNumberConfiguration { get; set; }
        public virtual DbSet<MS_LotNumberExpiry> MS_LotNumberExpiry { get; set; }
        public virtual DbSet<MS_PaymentNote> MS_PaymentNote { get; set; }
        public virtual DbSet<Ms_PaymentNoteCurrencies> Ms_PaymentNoteCurrencies { get; set; }
        public virtual DbSet<Ms_PaymentNoteItems> Ms_PaymentNoteItems { get; set; }
        public virtual DbSet<MS_Pettycash> MS_Pettycash { get; set; }
        public virtual DbSet<MS_PettyCashDetails> MS_PettyCashDetails { get; set; }
        public virtual DbSet<Ms_PettyPaymentJoin> Ms_PettyPaymentJoin { get; set; }
        public virtual DbSet<Ms_PosItemCategory> Ms_PosItemCategory { get; set; }
        public virtual DbSet<Ms_PosPaymentMethods> Ms_PosPaymentMethods { get; set; }
        public virtual DbSet<Ms_POSSettings> Ms_POSSettings { get; set; }
        public virtual DbSet<Ms_PosSpecialItems> Ms_PosSpecialItems { get; set; }
        public virtual DbSet<Ms_PurchaseInvoiceCostReceived> Ms_PurchaseInvoiceCostReceived { get; set; }
        public virtual DbSet<MS_PurchaseInvoiceExpenses> MS_PurchaseInvoiceExpenses { get; set; }
        public virtual DbSet<MS_PurchaseInvoiceItemCard> MS_PurchaseInvoiceItemCard { get; set; }
        public virtual DbSet<MS_PurchasInvoice> MS_PurchasInvoice { get; set; }
        public virtual DbSet<MS_PurchasInvoiceCurrencies> MS_PurchasInvoiceCurrencies { get; set; }
        public virtual DbSet<MS_PurchasInvoiceMultiAccounts> MS_PurchasInvoiceMultiAccounts { get; set; }
        public virtual DbSet<Ms_PurchasOrder> Ms_PurchasOrder { get; set; }
        public virtual DbSet<Ms_PurchasOrderRequest> Ms_PurchasOrderRequest { get; set; }
        public virtual DbSet<Ms_PurchInvVehicleJobOrderJoin> Ms_PurchInvVehicleJobOrderJoin { get; set; }
        public virtual DbSet<MS_PurchOrderDetail> MS_PurchOrderDetail { get; set; }
        public virtual DbSet<MS_PurchOrderReqDetail> MS_PurchOrderReqDetail { get; set; }
        public virtual DbSet<Ms_ReceiptNote> Ms_ReceiptNote { get; set; }
        public virtual DbSet<Ms_ReceiptNoteCurrencies> Ms_ReceiptNoteCurrencies { get; set; }
        public virtual DbSet<Ms_RecPayDocJoin> Ms_RecPayDocJoin { get; set; }
        public virtual DbSet<MS_ReturnPurchase> MS_ReturnPurchase { get; set; }
        public virtual DbSet<MS_ReturnPurchaseCurrencies> MS_ReturnPurchaseCurrencies { get; set; }
        public virtual DbSet<Ms_ReturnPurchaseExpenses> Ms_ReturnPurchaseExpenses { get; set; }
        public virtual DbSet<MS_ReturnPurchaseItem> MS_ReturnPurchaseItem { get; set; }
        public virtual DbSet<MS_ReturnPurchaseMultiAccounts> MS_ReturnPurchaseMultiAccounts { get; set; }
        public virtual DbSet<MS_ReturnSales> MS_ReturnSales { get; set; }
        public virtual DbSet<MS_ReturnSalesCurrencies> MS_ReturnSalesCurrencies { get; set; }
        public virtual DbSet<Ms_ReturnSalesExpenses> Ms_ReturnSalesExpenses { get; set; }
        public virtual DbSet<MS_ReturnSalesItemCard> MS_ReturnSalesItemCard { get; set; }
        public virtual DbSet<MS_ReturnSalesMultiAccounts> MS_ReturnSalesMultiAccounts { get; set; }
        public virtual DbSet<Ms_SalesInvJobOrderJoin> Ms_SalesInvJobOrderJoin { get; set; }
        public virtual DbSet<Ms_SalesInvoice> Ms_SalesInvoice { get; set; }
        public virtual DbSet<Ms_SalesInvoiceCurrencies> Ms_SalesInvoiceCurrencies { get; set; }
        public virtual DbSet<Ms_SalesInvoiceExpenses> Ms_SalesInvoiceExpenses { get; set; }
        public virtual DbSet<Ms_SalesInvoiceItemCard> Ms_SalesInvoiceItemCard { get; set; }
        public virtual DbSet<MS_SalesInvoiceItemCard_Deleted> MS_SalesInvoiceItemCard_Deleted { get; set; }
        public virtual DbSet<Ms_SalesInvoiceMultiAccounts> Ms_SalesInvoiceMultiAccounts { get; set; }
        public virtual DbSet<Ms_SalesInvoiceQualityDeliveryDocs> Ms_SalesInvoiceQualityDeliveryDocs { get; set; }
        public virtual DbSet<Ms_SalesInvoiceQualityMissedItems> Ms_SalesInvoiceQualityMissedItems { get; set; }
        public virtual DbSet<Ms_SalesInvVehiclJobOrderJoin> Ms_SalesInvVehiclJobOrderJoin { get; set; }
        public virtual DbSet<Ms_SalesItemsOffers> Ms_SalesItemsOffers { get; set; }
        public virtual DbSet<Ms_SalesItemsOffersDetails> Ms_SalesItemsOffersDetails { get; set; }
        public virtual DbSet<Ms_SalesOffer> Ms_SalesOffer { get; set; }
        public virtual DbSet<Ms_SalesOfferItemCard> Ms_SalesOfferItemCard { get; set; }
        public virtual DbSet<Ms_SalesOfferItemRequest> Ms_SalesOfferItemRequest { get; set; }
        public virtual DbSet<Ms_SalesOfferRequest> Ms_SalesOfferRequest { get; set; }
        public virtual DbSet<Ms_SalesOrder> Ms_SalesOrder { get; set; }
        public virtual DbSet<Ms_SalesOrderItemCard> Ms_SalesOrderItemCard { get; set; }
        public virtual DbSet<MS_Settings> MS_Settings { get; set; }
        public virtual DbSet<MS_StockReceiptItemCard> MS_StockReceiptItemCard { get; set; }
        public virtual DbSet<MS_StockRecript> MS_StockRecript { get; set; }
        public virtual DbSet<MS_StockRecriptExpenses> MS_StockRecriptExpenses { get; set; }
        public virtual DbSet<MS_StockRecriptMultiAccounts> MS_StockRecriptMultiAccounts { get; set; }
        public virtual DbSet<MS_StockTranItemCard> MS_StockTranItemCard { get; set; }
        public virtual DbSet<Ms_StockTranItemCardReq> Ms_StockTranItemCardReq { get; set; }
        public virtual DbSet<MS_StockTransferNote> MS_StockTransferNote { get; set; }
        public virtual DbSet<Ms_StockTransferNoteRequest> Ms_StockTransferNoteRequest { get; set; }
        public virtual DbSet<Ms_Terms> Ms_Terms { get; set; }
        public virtual DbSet<Ms_TermsCostCenter> Ms_TermsCostCenter { get; set; }
        public virtual DbSet<Ms_TermsDetails> Ms_TermsDetails { get; set; }
        public virtual DbSet<MS_UserAuthentications> MS_UserAuthentications { get; set; }
        public virtual DbSet<Ms_VendImgs> Ms_VendImgs { get; set; }
        public virtual DbSet<Ms_VendorBranches> Ms_VendorBranches { get; set; }
        public virtual DbSet<MS_VendorCategory> MS_VendorCategory { get; set; }
        public virtual DbSet<Ms_VendorContacts> Ms_VendorContacts { get; set; }
        public virtual DbSet<Ms_VendorUsers> Ms_VendorUsers { get; set; }
        public virtual DbSet<Ms_WeightCard> Ms_WeightCard { get; set; }
        public virtual DbSet<Ms_WeightcardItems> Ms_WeightcardItems { get; set; }
        public virtual DbSet<MsGA_Capacity> MsGA_Capacity { get; set; }
        public virtual DbSet<MSGA_City> MSGA_City { get; set; }
        public virtual DbSet<MsGA_LetterExport> MsGA_LetterExport { get; set; }
        public virtual DbSet<MsGA_LetterExportDetail> MsGA_LetterExportDetail { get; set; }
        public virtual DbSet<MsGA_LetterFayum> MsGA_LetterFayum { get; set; }
        public virtual DbSet<MsGA_LetterFayumDetail> MsGA_LetterFayumDetail { get; set; }
        public virtual DbSet<MsGA_LetterNormal> MsGA_LetterNormal { get; set; }
        public virtual DbSet<MsGA_LetterNormalDetail> MsGA_LetterNormalDetail { get; set; }
        public virtual DbSet<MsGA_MachineType> MsGA_MachineType { get; set; }
        public virtual DbSet<MsGA_Moror> MsGA_Moror { get; set; }
        public virtual DbSet<MsGA_MotorSN> MsGA_MotorSN { get; set; }
        public virtual DbSet<MsGA_MotorSNDetail> MsGA_MotorSNDetail { get; set; }
        public virtual DbSet<MsGA_Shipment> MsGA_Shipment { get; set; }
        public virtual DbSet<MsGA_ShipmentDetail> MsGA_ShipmentDetail { get; set; }
        public virtual DbSet<Prod_AttributeValue> Prod_AttributeValue { get; set; }
        public virtual DbSet<Prod_BasicUnits> Prod_BasicUnits { get; set; }
        public virtual DbSet<Prod_BillOfMaterial> Prod_BillOfMaterial { get; set; }
        public virtual DbSet<Prod_BillOfMaterialItems> Prod_BillOfMaterialItems { get; set; }
        public virtual DbSet<Prod_BillOfMaterialSecondaryItems> Prod_BillOfMaterialSecondaryItems { get; set; }
        public virtual DbSet<Prod_Equipments> Prod_Equipments { get; set; }
        public virtual DbSet<Prod_EquipProfile> Prod_EquipProfile { get; set; }
        public virtual DbSet<Prod_ItemAttributes> Prod_ItemAttributes { get; set; }
        public virtual DbSet<Prod_ItemAttributesBatche> Prod_ItemAttributesBatche { get; set; }
        public virtual DbSet<Prod_ItemAttributesBatchesDetails> Prod_ItemAttributesBatchesDetails { get; set; }
        public virtual DbSet<Prod_ItemAttributsJoin> Prod_ItemAttributsJoin { get; set; }
        public virtual DbSet<Prod_ItemBatchPartition> Prod_ItemBatchPartition { get; set; }
        public virtual DbSet<Prod_ItemcardExpenses> Prod_ItemcardExpenses { get; set; }
        public virtual DbSet<Prod_JobOrder> Prod_JobOrder { get; set; }
        public virtual DbSet<Prod_JobOrderClosing> Prod_JobOrderClosing { get; set; }
        public virtual DbSet<Prod_JobOrderEmpCostDoc> Prod_JobOrderEmpCostDoc { get; set; }
        public virtual DbSet<Prod_JobOrderEmpCostDocDetail> Prod_JobOrderEmpCostDocDetail { get; set; }
        public virtual DbSet<Prod_JobOrderEquipCostDoc> Prod_JobOrderEquipCostDoc { get; set; }
        public virtual DbSet<Prod_JobOrderEquipCostDocDetail> Prod_JobOrderEquipCostDocDetail { get; set; }
        public virtual DbSet<Prod_JobOrderEquipment> Prod_JobOrderEquipment { get; set; }
        public virtual DbSet<Prod_JobOrderExpenses> Prod_JobOrderExpenses { get; set; }
        public virtual DbSet<Prod_JobOrderGoStock> Prod_JobOrderGoStock { get; set; }
        public virtual DbSet<Prod_JobOrderJobs> Prod_JobOrderJobs { get; set; }
        public virtual DbSet<Prod_JobOrderMaterials> Prod_JobOrderMaterials { get; set; }
        public virtual DbSet<Prod_JobOrderProducts> Prod_JobOrderProducts { get; set; }
        public virtual DbSet<Prod_JobOrderPurchaseInvoices> Prod_JobOrderPurchaseInvoices { get; set; }
        public virtual DbSet<Prod_JobOrderScrap> Prod_JobOrderScrap { get; set; }
        public virtual DbSet<Prod_JobOrderServices> Prod_JobOrderServices { get; set; }
        public virtual DbSet<Prod_JobOrderTasks> Prod_JobOrderTasks { get; set; }
        public virtual DbSet<Prod_JobOrderType> Prod_JobOrderType { get; set; }
        public virtual DbSet<Prod_JobOrderWorkFlow> Prod_JobOrderWorkFlow { get; set; }
        public virtual DbSet<Prod_JoinTaskEquipments> Prod_JoinTaskEquipments { get; set; }
        public virtual DbSet<Prod_JoinTaskJob> Prod_JoinTaskJob { get; set; }
        public virtual DbSet<Prod_ProductionLine> Prod_ProductionLine { get; set; }
        public virtual DbSet<Prod_ProductionLineDetails> Prod_ProductionLineDetails { get; set; }
        public virtual DbSet<Prod_ProductionOrder> Prod_ProductionOrder { get; set; }
        public virtual DbSet<Prod_ProductionOrderDetail> Prod_ProductionOrderDetail { get; set; }
        public virtual DbSet<Prod_Recipe> Prod_Recipe { get; set; }
        public virtual DbSet<Prod_RecipeDetail> Prod_RecipeDetail { get; set; }
        public virtual DbSet<Prod_Settings> Prod_Settings { get; set; }
        public virtual DbSet<Prod_Tasks> Prod_Tasks { get; set; }
        public virtual DbSet<Prod_WorkOrder> Prod_WorkOrder { get; set; }
        public virtual DbSet<Prod_WorkOrderEquipment> Prod_WorkOrderEquipment { get; set; }
        public virtual DbSet<Prod_WorkOrderExpenses> Prod_WorkOrderExpenses { get; set; }
        public virtual DbSet<Prod_WorkOrderItemRecQualityDocs> Prod_WorkOrderItemRecQualityDocs { get; set; }
        public virtual DbSet<Prod_WorkOrderMaterials> Prod_WorkOrderMaterials { get; set; }
        public virtual DbSet<Prod_WorkOrderProdItems> Prod_WorkOrderProdItems { get; set; }
        public virtual DbSet<Prod_WorkOrderScrap> Prod_WorkOrderScrap { get; set; }
        public virtual DbSet<Prod_WorkOrderServices> Prod_WorkOrderServices { get; set; }
        public virtual DbSet<Proj_Accounts> Proj_Accounts { get; set; }
        public virtual DbSet<Proj_EstimateItems> Proj_EstimateItems { get; set; }
        public virtual DbSet<Proj_Expenses> Proj_Expenses { get; set; }
        public virtual DbSet<Proj_Fund> Proj_Fund { get; set; }
        public virtual DbSet<Proj_ProjectItemEmpJoin> Proj_ProjectItemEmpJoin { get; set; }
        public virtual DbSet<Proj_ProjectItems> Proj_ProjectItems { get; set; }
        public virtual DbSet<Proj_ProjectItemsJoin> Proj_ProjectItemsJoin { get; set; }
        public virtual DbSet<Proj_ProjectItemsVendors> Proj_ProjectItemsVendors { get; set; }
        public virtual DbSet<Proj_Projects> Proj_Projects { get; set; }
        public virtual DbSet<Proj_ProjExploitJoin> Proj_ProjExploitJoin { get; set; }
        public virtual DbSet<Proj_ProjInsurance> Proj_ProjInsurance { get; set; }
        public virtual DbSet<Proj_ProjInsuranceUnit> Proj_ProjInsuranceUnit { get; set; }
        public virtual DbSet<Proj_ProjItemEmpTaskJoin> Proj_ProjItemEmpTaskJoin { get; set; }
        public virtual DbSet<Proj_ProjOccupTypeJoin> Proj_ProjOccupTypeJoin { get; set; }
        public virtual DbSet<Proj_ProjOwnerJoin> Proj_ProjOwnerJoin { get; set; }
        public virtual DbSet<Proj_ProjParkingJoin> Proj_ProjParkingJoin { get; set; }
        public virtual DbSet<Proj_ProjPermitActivityJoin> Proj_ProjPermitActivityJoin { get; set; }
        public virtual DbSet<Proj_ProjUnitExploitJoin> Proj_ProjUnitExploitJoin { get; set; }
        public virtual DbSet<Proj_ProjUnitInstallTemp> Proj_ProjUnitInstallTemp { get; set; }
        public virtual DbSet<Proj_ProjUnitOccupTypeJoin> Proj_ProjUnitOccupTypeJoin { get; set; }
        public virtual DbSet<Proj_ProjUnitOwnerJoin> Proj_ProjUnitOwnerJoin { get; set; }
        public virtual DbSet<Proj_ProjUnitPermitActivityJoin> Proj_ProjUnitPermitActivityJoin { get; set; }
        public virtual DbSet<Proj_ProjUnits> Proj_ProjUnits { get; set; }
        public virtual DbSet<Proj_ProjUnitService> Proj_ProjUnitService { get; set; }
        public virtual DbSet<Proj_ProjUnitSubUnits> Proj_ProjUnitSubUnits { get; set; }
        public virtual DbSet<Proj_RealItems> Proj_RealItems { get; set; }
        public virtual DbSet<Proj_ReInstallment> Proj_ReInstallment { get; set; }
        public virtual DbSet<Proj_ReserveUnitOwners> Proj_ReserveUnitOwners { get; set; }
        public virtual DbSet<Proj_ReserveUnitSellers> Proj_ReserveUnitSellers { get; set; }
        public virtual DbSet<Proj_ReservInstallments> Proj_ReservInstallments { get; set; }
        public virtual DbSet<Proj_UnitConcession> Proj_UnitConcession { get; set; }
        public virtual DbSet<Proj_UnitHistoryLog> Proj_UnitHistoryLog { get; set; }
        public virtual DbSet<Proj_UnitReplacement> Proj_UnitReplacement { get; set; }
        public virtual DbSet<Proj_UnitReservation> Proj_UnitReservation { get; set; }
        public virtual DbSet<Quality_Categories> Quality_Categories { get; set; }
        public virtual DbSet<Quality_ItemDeliverDetails> Quality_ItemDeliverDetails { get; set; }
        public virtual DbSet<Quality_ItemDelivery> Quality_ItemDelivery { get; set; }
        public virtual DbSet<Quality_ItemDeliveryPackages> Quality_ItemDeliveryPackages { get; set; }
        public virtual DbSet<Quality_ItemRecCheck> Quality_ItemRecCheck { get; set; }
        public virtual DbSet<Quality_ItemRecCheckDetail> Quality_ItemRecCheckDetail { get; set; }
        public virtual DbSet<Quality_ItemReceivTypes> Quality_ItemReceivTypes { get; set; }
        public virtual DbSet<Quality_ItemRecieve> Quality_ItemRecieve { get; set; }
        public virtual DbSet<Quality_ItemRecieveDetails> Quality_ItemRecieveDetails { get; set; }
        public virtual DbSet<Quality_ItemRecPackages> Quality_ItemRecPackages { get; set; }
        public virtual DbSet<Repair_JobOrder> Repair_JobOrder { get; set; }
        public virtual DbSet<Repair_JobOrderComments> Repair_JobOrderComments { get; set; }
        public virtual DbSet<Repair_JobOrderEmps> Repair_JobOrderEmps { get; set; }
        public virtual DbSet<Repair_JobOrderItems> Repair_JobOrderItems { get; set; }
        public virtual DbSet<Repair_JobOrderScrapItems> Repair_JobOrderScrapItems { get; set; }
        public virtual DbSet<Repair_JobOrederExpenses> Repair_JobOrederExpenses { get; set; }
        public virtual DbSet<Sr_Accomodation> Sr_Accomodation { get; set; }
        public virtual DbSet<Sr_Complaints> Sr_Complaints { get; set; }
        public virtual DbSet<Sr_ContainerTypes> Sr_ContainerTypes { get; set; }
        public virtual DbSet<Sr_Drivers> Sr_Drivers { get; set; }
        public virtual DbSet<Sr_EmpServicTypes> Sr_EmpServicTypes { get; set; }
        public virtual DbSet<Sr_Extension> Sr_Extension { get; set; }
        public virtual DbSet<Sr_Flight> Sr_Flight { get; set; }
        public virtual DbSet<Sr_Garage> Sr_Garage { get; set; }
        public virtual DbSet<Sr_Harbors> Sr_Harbors { get; set; }
        public virtual DbSet<Sr_Hotels> Sr_Hotels { get; set; }
        public virtual DbSet<Sr_JobAdditionalCost> Sr_JobAdditionalCost { get; set; }
        public virtual DbSet<Sr_JobComments> Sr_JobComments { get; set; }
        public virtual DbSet<Sr_JobExtrnalExpens> Sr_JobExtrnalExpens { get; set; }
        public virtual DbSet<Sr_JobFiles> Sr_JobFiles { get; set; }
        public virtual DbSet<Sr_JobOrder> Sr_JobOrder { get; set; }
        public virtual DbSet<Sr_JobSparts> Sr_JobSparts { get; set; }
        public virtual DbSet<Sr_JobSWages> Sr_JobSWages { get; set; }
        public virtual DbSet<Sr_Programs> Sr_Programs { get; set; }
        public virtual DbSet<Sr_ReceptionImages> Sr_ReceptionImages { get; set; }
        public virtual DbSet<Sr_Reciption> Sr_Reciption { get; set; }
        public virtual DbSet<Sr_ReciptionDetail> Sr_ReciptionDetail { get; set; }
        public virtual DbSet<Sr_ReqOfQoutation> Sr_ReqOfQoutation { get; set; }
        public virtual DbSet<Sr_ServiceTypes> Sr_ServiceTypes { get; set; }
        public virtual DbSet<Sr_ShippingDeclaration> Sr_ShippingDeclaration { get; set; }
        public virtual DbSet<Sr_TaskEmp> Sr_TaskEmp { get; set; }
        public virtual DbSet<Sr_TaskItem> Sr_TaskItem { get; set; }
        public virtual DbSet<Sr_Tasks> Sr_Tasks { get; set; }
        public virtual DbSet<Sr_TrafficLinePriceList> Sr_TrafficLinePriceList { get; set; }
        public virtual DbSet<Sr_TrafficLines> Sr_TrafficLines { get; set; }
        public virtual DbSet<Sr_Transportation> Sr_Transportation { get; set; }
        public virtual DbSet<Sr_TripAccomDetail> Sr_TripAccomDetail { get; set; }
        public virtual DbSet<Sr_TripProgramJoin> Sr_TripProgramJoin { get; set; }
        public virtual DbSet<Sr_Trips> Sr_Trips { get; set; }
        public virtual DbSet<Sr_VehicleItemCard> Sr_VehicleItemCard { get; set; }
        public virtual DbSet<Sr_VehicleJobOrder> Sr_VehicleJobOrder { get; set; }
        public virtual DbSet<Sr_VehicleJobOrderDetail> Sr_VehicleJobOrderDetail { get; set; }
        public virtual DbSet<Sr_VehicleRenalContract> Sr_VehicleRenalContract { get; set; }
        public virtual DbSet<Sr_VehicleRentPayJoin> Sr_VehicleRentPayJoin { get; set; }
        public virtual DbSet<Sr_VehicleRentPurchJoin> Sr_VehicleRentPurchJoin { get; set; }
        public virtual DbSet<Sr_VehicleRentRecJoin> Sr_VehicleRentRecJoin { get; set; }
        public virtual DbSet<Sr_VehicleRentSalesInvJoin> Sr_VehicleRentSalesInvJoin { get; set; }
        public virtual DbSet<Sr_Vehicles> Sr_Vehicles { get; set; }
        public virtual DbSet<Sr_VehicleShapes> Sr_VehicleShapes { get; set; }
        public virtual DbSet<Sr_VehicleTypes> Sr_VehicleTypes { get; set; }
        public virtual DbSet<Sr_VheicleJobOrderType> Sr_VheicleJobOrderType { get; set; }
        public virtual DbSet<Sr_Warranty> Sr_Warranty { get; set; }
        public virtual DbSet<Stock_Archives> Stock_Archives { get; set; }
        public virtual DbSet<Stock_Brokers> Stock_Brokers { get; set; }
        public virtual DbSet<Stock_CapitalUpdate> Stock_CapitalUpdate { get; set; }
        public virtual DbSet<Stock_CashTransfer> Stock_CashTransfer { get; set; }
        public virtual DbSet<Stock_CashWithdrawalReasons> Stock_CashWithdrawalReasons { get; set; }
        public virtual DbSet<Stock_Categories> Stock_Categories { get; set; }
        public virtual DbSet<Stock_Dealers> Stock_Dealers { get; set; }
        public virtual DbSet<Stock_Markets> Stock_Markets { get; set; }
        public virtual DbSet<Stock_OpenningBalance> Stock_OpenningBalance { get; set; }
        public virtual DbSet<Stock_OpenningBalanceDetails> Stock_OpenningBalanceDetails { get; set; }
        public virtual DbSet<Stock_Portfolio> Stock_Portfolio { get; set; }
        public virtual DbSet<Stock_PortfolioAccounts> Stock_PortfolioAccounts { get; set; }
        public virtual DbSet<Stock_PortfolioStockArchives> Stock_PortfolioStockArchives { get; set; }
        public virtual DbSet<Stock_PortfolioStocks> Stock_PortfolioStocks { get; set; }
        public virtual DbSet<Stock_SalesPurchase> Stock_SalesPurchase { get; set; }
        public virtual DbSet<Stock_SalesPurchaseDetails> Stock_SalesPurchaseDetails { get; set; }
        public virtual DbSet<Stock_Sectors> Stock_Sectors { get; set; }
        public virtual DbSet<Stock_ShareholdersNames> Stock_ShareholdersNames { get; set; }
        public virtual DbSet<Stock_Stocks> Stock_Stocks { get; set; }
        public virtual DbSet<Stock_Transfer> Stock_Transfer { get; set; }
        public virtual DbSet<Stock_TransferDetail> Stock_TransferDetail { get; set; }
        public virtual DbSet<Stock_TranTypes> Stock_TranTypes { get; set; }
        public virtual DbSet<sys_AnalyticalCodeProccess> sys_AnalyticalCodeProccess { get; set; }
        public virtual DbSet<Sys_AnalyticalCodes> Sys_AnalyticalCodes { get; set; }
        public virtual DbSet<sys_AnalyticalCodeUpdates> sys_AnalyticalCodeUpdates { get; set; }
        public virtual DbSet<sys_AnalyticalCodeUpdateTypes> sys_AnalyticalCodeUpdateTypes { get; set; }
        public virtual DbSet<Sys_Basket> Sys_Basket { get; set; }
        public virtual DbSet<Sys_Books> Sys_Books { get; set; }
        public virtual DbSet<Sys_City> Sys_City { get; set; }
        public virtual DbSet<Sys_Counter> Sys_Counter { get; set; }
        public virtual DbSet<Sys_Countries> Sys_Countries { get; set; }
        public virtual DbSet<Sys_FinancialIntervals> Sys_FinancialIntervals { get; set; }
        public virtual DbSet<Sys_FinancialYears> Sys_FinancialYears { get; set; }
        public virtual DbSet<Sys_FinancialYearsClosing> Sys_FinancialYearsClosing { get; set; }
        public virtual DbSet<sys_FlexLists> sys_FlexLists { get; set; }
        public virtual DbSet<Sys_Naming> Sys_Naming { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tr_OpenningBalance> Tr_OpenningBalance { get; set; }
        public virtual DbSet<Tr_OpenningBalanceDetails> Tr_OpenningBalanceDetails { get; set; }
        public virtual DbSet<YearMonthes> YearMonthes { get; set; }
        public virtual DbSet<MS_Vendor> MS_Vendor { get; set; }
        public virtual DbSet<Hr_Employees> Hr_Employees { get; set; }
        public virtual DbSet<Cal_Clauses> Cal_Clauses { get; set; }
        public virtual DbSet<VW_SearchAllAccounts> VW_SearchAllAccounts { get; set; }
        public virtual DbSet<G_USERS> G_USERS { get; set; }
        public virtual DbSet<MS_Taxes> MS_Taxes { get; set; }
        public virtual DbSet<MS_ItemImages> MS_ItemImages { get; set; }
        public virtual DbSet<G_SearchForm> G_SearchForm { get; set; }
        public virtual DbSet<G_SearchFormSetting> G_SearchFormSetting { get; set; }
        public virtual DbSet<G_SearchFormModule> G_SearchFormModule { get; set; }
    
        public virtual int G_ProcessTrans(Nullable<int> comp, Nullable<int> branch, string trType, string opMode, Nullable<int> trID, ObjectParameter trNo, ObjectParameter ok)
        {
            var compParameter = comp.HasValue ?
                new ObjectParameter("Comp", comp) :
                new ObjectParameter("Comp", typeof(int));
    
            var branchParameter = branch.HasValue ?
                new ObjectParameter("Branch", branch) :
                new ObjectParameter("Branch", typeof(int));
    
            var trTypeParameter = trType != null ?
                new ObjectParameter("TrType", trType) :
                new ObjectParameter("TrType", typeof(string));
    
            var opModeParameter = opMode != null ?
                new ObjectParameter("OpMode", opMode) :
                new ObjectParameter("OpMode", typeof(string));
    
            var trIDParameter = trID.HasValue ?
                new ObjectParameter("TrID", trID) :
                new ObjectParameter("TrID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("G_ProcessTrans", compParameter, branchParameter, trTypeParameter, opModeParameter, trIDParameter, trNo, ok);
        }
    
        [DbFunction("InvEntities", "GFun_Companies")]
        public virtual IQueryable<GFun_Companies_Result> GFun_Companies(string userCode)
        {
            var userCodeParameter = userCode != null ?
                new ObjectParameter("userCode", userCode) :
                new ObjectParameter("userCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GFun_Companies_Result>("[InvEntities].[GFun_Companies](@userCode)", userCodeParameter);
        }
    
        [DbFunction("InvEntities", "GFun_UserCompanyBranch")]
        public virtual IQueryable<GFun_UserCompanyBranch_Result> GFun_UserCompanyBranch(string userCode, Nullable<int> compCode)
        {
            var userCodeParameter = userCode != null ?
                new ObjectParameter("userCode", userCode) :
                new ObjectParameter("userCode", typeof(string));
    
            var compCodeParameter = compCode.HasValue ?
                new ObjectParameter("CompCode", compCode) :
                new ObjectParameter("CompCode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GFun_UserCompanyBranch_Result>("[InvEntities].[GFun_UserCompanyBranch](@userCode, @CompCode)", userCodeParameter, compCodeParameter);
        }
    
        [DbFunction("InvEntities", "GFunc_GetPrivilage")]
        public virtual IQueryable<GFunc_GetPrivilage_Result> GFunc_GetPrivilage(Nullable<int> year, Nullable<int> comp, Nullable<int> bra, string user, string sys, string mod)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var compParameter = comp.HasValue ?
                new ObjectParameter("Comp", comp) :
                new ObjectParameter("Comp", typeof(int));
    
            var braParameter = bra.HasValue ?
                new ObjectParameter("bra", bra) :
                new ObjectParameter("bra", typeof(int));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var sysParameter = sys != null ?
                new ObjectParameter("Sys", sys) :
                new ObjectParameter("Sys", typeof(string));
    
            var modParameter = mod != null ?
                new ObjectParameter("Mod", mod) :
                new ObjectParameter("Mod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GFunc_GetPrivilage_Result>("[InvEntities].[GFunc_GetPrivilage](@year, @Comp, @bra, @user, @Sys, @Mod)", yearParameter, compParameter, braParameter, userParameter, sysParameter, modParameter);
        }
    
        [DbFunction("InvEntities", "GFunc_GetPrivilageRole")]
        public virtual IQueryable<GFunc_GetPrivilageRole_Result> GFunc_GetPrivilageRole(Nullable<int> comp, Nullable<int> bra, string user, string sys, string sub, string mod)
        {
            var compParameter = comp.HasValue ?
                new ObjectParameter("Comp", comp) :
                new ObjectParameter("Comp", typeof(int));
    
            var braParameter = bra.HasValue ?
                new ObjectParameter("bra", bra) :
                new ObjectParameter("bra", typeof(int));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var sysParameter = sys != null ?
                new ObjectParameter("Sys", sys) :
                new ObjectParameter("Sys", typeof(string));
    
            var subParameter = sub != null ?
                new ObjectParameter("sub", sub) :
                new ObjectParameter("sub", typeof(string));
    
            var modParameter = mod != null ?
                new ObjectParameter("Mod", mod) :
                new ObjectParameter("Mod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GFunc_GetPrivilageRole_Result>("[InvEntities].[GFunc_GetPrivilageRole](@Comp, @bra, @user, @Sys, @sub, @Mod)", compParameter, braParameter, userParameter, sysParameter, subParameter, modParameter);
        }
    
        public virtual ObjectResult<RptCustomerBalanceDetail_Result> RptCustomerBalanceDetail(string customerCodeFrom, string customerCodeTo, Nullable<decimal> custBalanceFrom, Nullable<decimal> custBalanceTo, Nullable<bool> custStatus, string catCodeFrom, string catCodeTo)
        {
            var customerCodeFromParameter = customerCodeFrom != null ?
                new ObjectParameter("CustomerCodeFrom", customerCodeFrom) :
                new ObjectParameter("CustomerCodeFrom", typeof(string));
    
            var customerCodeToParameter = customerCodeTo != null ?
                new ObjectParameter("CustomerCodeTo", customerCodeTo) :
                new ObjectParameter("CustomerCodeTo", typeof(string));
    
            var custBalanceFromParameter = custBalanceFrom.HasValue ?
                new ObjectParameter("CustBalanceFrom", custBalanceFrom) :
                new ObjectParameter("CustBalanceFrom", typeof(decimal));
    
            var custBalanceToParameter = custBalanceTo.HasValue ?
                new ObjectParameter("CustBalanceTo", custBalanceTo) :
                new ObjectParameter("CustBalanceTo", typeof(decimal));
    
            var custStatusParameter = custStatus.HasValue ?
                new ObjectParameter("CustStatus", custStatus) :
                new ObjectParameter("CustStatus", typeof(bool));
    
            var catCodeFromParameter = catCodeFrom != null ?
                new ObjectParameter("CatCodeFrom", catCodeFrom) :
                new ObjectParameter("CatCodeFrom", typeof(string));
    
            var catCodeToParameter = catCodeTo != null ?
                new ObjectParameter("CatCodeTo", catCodeTo) :
                new ObjectParameter("CatCodeTo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RptCustomerBalanceDetail_Result>("RptCustomerBalanceDetail", customerCodeFromParameter, customerCodeToParameter, custBalanceFromParameter, custBalanceToParameter, custStatusParameter, catCodeFromParameter, catCodeToParameter);
        }
    
        public virtual ObjectResult<RptCustomerDetail_Result> RptCustomerDetail(string customerCodeFrom, string customerCodeTo, Nullable<decimal> custBalanceFrom, Nullable<decimal> custBalanceTo, Nullable<bool> custStatus, string catCodeFrom, string catCodeTo)
        {
            var customerCodeFromParameter = customerCodeFrom != null ?
                new ObjectParameter("CustomerCodeFrom", customerCodeFrom) :
                new ObjectParameter("CustomerCodeFrom", typeof(string));
    
            var customerCodeToParameter = customerCodeTo != null ?
                new ObjectParameter("CustomerCodeTo", customerCodeTo) :
                new ObjectParameter("CustomerCodeTo", typeof(string));
    
            var custBalanceFromParameter = custBalanceFrom.HasValue ?
                new ObjectParameter("CustBalanceFrom", custBalanceFrom) :
                new ObjectParameter("CustBalanceFrom", typeof(decimal));
    
            var custBalanceToParameter = custBalanceTo.HasValue ?
                new ObjectParameter("CustBalanceTo", custBalanceTo) :
                new ObjectParameter("CustBalanceTo", typeof(decimal));
    
            var custStatusParameter = custStatus.HasValue ?
                new ObjectParameter("CustStatus", custStatus) :
                new ObjectParameter("CustStatus", typeof(bool));
    
            var catCodeFromParameter = catCodeFrom != null ?
                new ObjectParameter("CatCodeFrom", catCodeFrom) :
                new ObjectParameter("CatCodeFrom", typeof(string));
    
            var catCodeToParameter = catCodeTo != null ?
                new ObjectParameter("CatCodeTo", catCodeTo) :
                new ObjectParameter("CatCodeTo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RptCustomerDetail_Result>("RptCustomerDetail", customerCodeFromParameter, customerCodeToParameter, custBalanceFromParameter, custBalanceToParameter, custStatusParameter, catCodeFromParameter, catCodeToParameter);
        }
    
        public virtual ObjectResult<RptCustomerInfo_Result> RptCustomerInfo(string customerCode, string catCodeFrom, string catCodeTo)
        {
            var customerCodeParameter = customerCode != null ?
                new ObjectParameter("CustomerCode", customerCode) :
                new ObjectParameter("CustomerCode", typeof(string));
    
            var catCodeFromParameter = catCodeFrom != null ?
                new ObjectParameter("CatCodeFrom", catCodeFrom) :
                new ObjectParameter("CatCodeFrom", typeof(string));
    
            var catCodeToParameter = catCodeTo != null ?
                new ObjectParameter("CatCodeTo", catCodeTo) :
                new ObjectParameter("CatCodeTo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RptCustomerInfo_Result>("RptCustomerInfo", customerCodeParameter, catCodeFromParameter, catCodeToParameter);
        }
    
        public virtual ObjectResult<RptCustomerItem_Result> RptCustomerItem(Nullable<System.DateTime> trdateFrom, Nullable<System.DateTime> trdateTo, Nullable<int> trNoFrom, Nullable<int> trNoTo, string itemCodeFrom, string itemCodeTo)
        {
            var trdateFromParameter = trdateFrom.HasValue ?
                new ObjectParameter("TrdateFrom", trdateFrom) :
                new ObjectParameter("TrdateFrom", typeof(System.DateTime));
    
            var trdateToParameter = trdateTo.HasValue ?
                new ObjectParameter("TrdateTo", trdateTo) :
                new ObjectParameter("TrdateTo", typeof(System.DateTime));
    
            var trNoFromParameter = trNoFrom.HasValue ?
                new ObjectParameter("TrNoFrom", trNoFrom) :
                new ObjectParameter("TrNoFrom", typeof(int));
    
            var trNoToParameter = trNoTo.HasValue ?
                new ObjectParameter("TrNoTo", trNoTo) :
                new ObjectParameter("TrNoTo", typeof(int));
    
            var itemCodeFromParameter = itemCodeFrom != null ?
                new ObjectParameter("ItemCodeFrom", itemCodeFrom) :
                new ObjectParameter("ItemCodeFrom", typeof(string));
    
            var itemCodeToParameter = itemCodeTo != null ?
                new ObjectParameter("ItemCodeTo", itemCodeTo) :
                new ObjectParameter("ItemCodeTo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RptCustomerItem_Result>("RptCustomerItem", trdateFromParameter, trdateToParameter, trNoFromParameter, trNoToParameter, itemCodeFromParameter, itemCodeToParameter);
        }
    
        public virtual ObjectResult<RPTCustomerPreviousBalance_Result> RPTCustomerPreviousBalance(string customerCodeFrom, string customerCodeTo, Nullable<System.DateTime> trdateFrom, Nullable<System.DateTime> trdateTo, Nullable<int> custAccountId)
        {
            var customerCodeFromParameter = customerCodeFrom != null ?
                new ObjectParameter("CustomerCodeFrom", customerCodeFrom) :
                new ObjectParameter("CustomerCodeFrom", typeof(string));
    
            var customerCodeToParameter = customerCodeTo != null ?
                new ObjectParameter("CustomerCodeTo", customerCodeTo) :
                new ObjectParameter("CustomerCodeTo", typeof(string));
    
            var trdateFromParameter = trdateFrom.HasValue ?
                new ObjectParameter("TrdateFrom", trdateFrom) :
                new ObjectParameter("TrdateFrom", typeof(System.DateTime));
    
            var trdateToParameter = trdateTo.HasValue ?
                new ObjectParameter("TrdateTo", trdateTo) :
                new ObjectParameter("TrdateTo", typeof(System.DateTime));
    
            var custAccountIdParameter = custAccountId.HasValue ?
                new ObjectParameter("CustAccountId", custAccountId) :
                new ObjectParameter("CustAccountId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPTCustomerPreviousBalance_Result>("RPTCustomerPreviousBalance", customerCodeFromParameter, customerCodeToParameter, trdateFromParameter, trdateToParameter, custAccountIdParameter);
        }
    
        public virtual ObjectResult<RptCustomersLicenses_Result> RptCustomersLicenses(string customerCodeFrom, string customerCodeTo, Nullable<System.DateTime> trdateFrom, Nullable<System.DateTime> trdateTo)
        {
            var customerCodeFromParameter = customerCodeFrom != null ?
                new ObjectParameter("CustomerCodeFrom", customerCodeFrom) :
                new ObjectParameter("CustomerCodeFrom", typeof(string));
    
            var customerCodeToParameter = customerCodeTo != null ?
                new ObjectParameter("CustomerCodeTo", customerCodeTo) :
                new ObjectParameter("CustomerCodeTo", typeof(string));
    
            var trdateFromParameter = trdateFrom.HasValue ?
                new ObjectParameter("TrdateFrom", trdateFrom) :
                new ObjectParameter("TrdateFrom", typeof(System.DateTime));
    
            var trdateToParameter = trdateTo.HasValue ?
                new ObjectParameter("TrdateTo", trdateTo) :
                new ObjectParameter("TrdateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RptCustomersLicenses_Result>("RptCustomersLicenses", customerCodeFromParameter, customerCodeToParameter, trdateFromParameter, trdateToParameter);
        }
    
        public virtual ObjectResult<RPTCustomerStatement_Result> RPTCustomerStatement(string customerCodeFrom, string customerCodeTo, Nullable<System.DateTime> trdateFrom, Nullable<System.DateTime> trdateTo, Nullable<int> custAccountId)
        {
            var customerCodeFromParameter = customerCodeFrom != null ?
                new ObjectParameter("CustomerCodeFrom", customerCodeFrom) :
                new ObjectParameter("CustomerCodeFrom", typeof(string));
    
            var customerCodeToParameter = customerCodeTo != null ?
                new ObjectParameter("CustomerCodeTo", customerCodeTo) :
                new ObjectParameter("CustomerCodeTo", typeof(string));
    
            var trdateFromParameter = trdateFrom.HasValue ?
                new ObjectParameter("TrdateFrom", trdateFrom) :
                new ObjectParameter("TrdateFrom", typeof(System.DateTime));
    
            var trdateToParameter = trdateTo.HasValue ?
                new ObjectParameter("TrdateTo", trdateTo) :
                new ObjectParameter("TrdateTo", typeof(System.DateTime));
    
            var custAccountIdParameter = custAccountId.HasValue ?
                new ObjectParameter("CustAccountId", custAccountId) :
                new ObjectParameter("CustAccountId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPTCustomerStatement_Result>("RPTCustomerStatement", customerCodeFromParameter, customerCodeToParameter, trdateFromParameter, trdateToParameter, custAccountIdParameter);
        }
    
        public virtual ObjectResult<GetAllJurnalDetailes_Result> GetAllJurnalDetailes(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllJurnalDetailes_Result>("GetAllJurnalDetailes", idParameter);
        }
    }
}
