//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ms_Attachments
    {
        public int AttachId { get; set; }
        public string TableCode { get; set; }
        public Nullable<int> TableEntityId { get; set; }
        public string AttachType { get; set; }
        public string AttachPath { get; set; }
        public string AttachPath2 { get; set; }
        public string AttachDesc1 { get; set; }
        public string AttachDesc2 { get; set; }
        public Nullable<int> AttachSerial { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> RenewalDate { get; set; }
        public string IssuePlace { get; set; }
        public Nullable<bool> Encrypted { get; set; }
        public string EncyptionDesc { get; set; }
    }
}
