//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_BoxTransferDetail
    {
        public int BoxTranDetailId { get; set; }
        public Nullable<int> BoxTranId { get; set; }
        public Nullable<int> BoxFrom { get; set; }
        public Nullable<int> BoxTo { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> valu { get; set; }
    }
}
