//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_BoxBank
    {
        public int BoxId { get; set; }
        public string BoxCode { get; set; }
        public string DESCA { get; set; }
        public string DESCE { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string KeeperName { get; set; }
        public string BankResposableName { get; set; }
        public string BankTel { get; set; }
        public string BankMobile { get; set; }
        public string BankFax { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsBank { get; set; }
        public Nullable<int> CheckPrintID { get; set; }
        public Nullable<bool> ForAdjustOnly { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    }
}
