//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_BoxCurrency
    {
        public int BoxCurrencyId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> BoxId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> AccountChrtId { get; set; }
        public Nullable<int> RetAccountId { get; set; }
        public Nullable<int> BankExpensAccId { get; set; }
        public Nullable<int> ChequndercollectId { get; set; }
    }
}
