//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_Company
    {
        public int CompanyId { get; set; }
        public Nullable<int> code { get; set; }
        public string CompShortNameA { get; set; }
        public string CompShortNameE { get; set; }
        public string CompNameA { get; set; }
        public string CompNameE { get; set; }
        public string OwnerName { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string MailBox { get; set; }
        public string Address { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Tel3 { get; set; }
        public string Tel4 { get; set; }
        public string Fax1 { get; set; }
        public string Fax2 { get; set; }
        public string Fax3 { get; set; }
        public string Fax4 { get; set; }
        public string Mobile { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string Mobile3 { get; set; }
        public string Email { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Email3 { get; set; }
        public string Website { get; set; }
        public string Website3 { get; set; }
        public string Website2 { get; set; }
        public string Website1 { get; set; }
        public Nullable<System.DateTime> DateOfEstablishment { get; set; }
        public byte[] Logo { get; set; }
        public string LegalEntity { get; set; }
        public string RemarksA { get; set; }
        public string RemarksE { get; set; }
        public Nullable<System.DateTime> YearStartfrom { get; set; }
        public Nullable<System.DateTime> YearEndTo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    }
}
