//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ms_ChequesOpenning
    {
        public int ChequeOpenId { get; set; }
        public Nullable<bool> InOrOut { get; set; }
        public Nullable<bool> IsKembiala { get; set; }
        public Nullable<int> beneficiaryAccId { get; set; }
        public Nullable<bool> IsHelpingAccount { get; set; }
        public string HelpTableName { get; set; }
        public Nullable<int> BoxCurrencyId { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> ValueBeforeRate { get; set; }
        public string ChequeNumber { get; set; }
        public string Remarks { get; set; }
        public Nullable<byte> CheckType { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    }
}
