//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_CashTransactionDetail
    {
        public int PaidDocId { get; set; }
        public Nullable<int> RectId { get; set; }
        public Nullable<int> PayId { get; set; }
        public Nullable<int> AdjustId { get; set; }
        public Nullable<int> JurnalId { get; set; }
        public string TableCode { get; set; }
        public Nullable<int> TableId { get; set; }
        public Nullable<byte> TermType { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string TrNoDesc { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> NotPaid { get; set; }
        public Nullable<decimal> PaidByDoc { get; set; }
        public Nullable<decimal> TotalBeforRate { get; set; }
        public Nullable<decimal> PaidBeforeRate { get; set; }
        public Nullable<decimal> NotPaidBeforeRate { get; set; }
        public Nullable<decimal> PaidByDocBeforeRate { get; set; }
        public string Description { get; set; }
        public string Remarks1 { get; set; }
        public string Remarks2 { get; set; }
    }
}
