//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ms_CheqBooks
    {
        public int CheqBookId { get; set; }
        public string CheqBookCode { get; set; }
        public string CheqBookNamAR { get; set; }
        public string CheqBookNamEN { get; set; }
        public Nullable<int> StartAt { get; set; }
        public Nullable<int> CheqNum { get; set; }
        public Nullable<int> CurrentNum { get; set; }
        public Nullable<bool> Active { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<bool> EmpDefaultBook { get; set; }
    }
}
