//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ms_CurrencyRate
    {
        public int EqualCurrencyPriceId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> EquivalentCurrencyId { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<System.DateTime> LastModify { get; set; }
    }
}
