//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_Currency
    {
        public int CurrencyId { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyDescA { get; set; }
        public string CurrencyDescE { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<bool> DefualtCurrency { get; set; }
        public string CurrencySymbol { get; set; }
        public string fractionalUnit { get; set; }
        public Nullable<byte> DecimalPlaces { get; set; }
        public Nullable<int> CurrencyCategoryId { get; set; }
        public string CurrenctType { get; set; }
        public string singleCurencyname { get; set; }
        public string singleCurencyname2 { get; set; }
        public string DoubleCurencyname { get; set; }
        public string DoubleCurencyname2 { get; set; }
        public string CurrancyNameOverthree { get; set; }
        public string CurrancyNameOverthree2 { get; set; }
        public string CollectionCurrencyName { get; set; }
        public string CollectionCurrencyName2 { get; set; }
        public string singleCurencyFractionname { get; set; }
        public string singleCurencyFractionname2 { get; set; }
        public string DoubleCurencyFractionname { get; set; }
        public string DoubleCurencyFractionname2 { get; set; }
        public string CurrancyNameFractionOverthree { get; set; }
        public string CurrancyNameFractionOverthree2 { get; set; }
        public string CollectionCurrencyFractionName { get; set; }
        public string CollectionCurrencyFractionName2 { get; set; }
        public string singleCurencyTempname { get; set; }
        public string DoubleCurencyTempname { get; set; }
        public string CurrancyNameTempOver3 { get; set; }
        public string CollectionCurrencyTempName { get; set; }
        public Nullable<int> Aid { get; set; }
        public Nullable<decimal> EquivalentConversionPrice { get; set; }
        public Nullable<System.DateTime> LastModify { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    }
}
