//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ms_DeliverSalesInvoice
    {
        public int DeliverId { get; set; }
        public Nullable<int> InvId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> StorePartId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> RetPurchId { get; set; }
        public Nullable<int> JobOrderId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<int> TermId { get; set; }
        public Nullable<int> FinancialIntervalsId { get; set; }
        public string DBTableName { get; set; }
        public Nullable<int> DBTableId { get; set; }
        public string AccountTableName { get; set; }
        public Nullable<byte> RectSourceType { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> AId { get; set; }
        public int TrNo { get; set; }
        public string ManualTrNo { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
        public Nullable<decimal> DeliverQtyOut { get; set; }
        public Nullable<decimal> DeliverQty { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public string strCustm4 { get; set; }
        public string strCustm5 { get; set; }
        public string Remarks { get; set; }
        public string AddField3 { get; set; }
        public string AddField4 { get; set; }
        public string AddField5 { get; set; }
        public string AddField6 { get; set; }
        public string AddField7 { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<bool> IsPrinted { get; set; }
        public Nullable<decimal> NetPriceFromInv { get; set; }
        public Nullable<decimal> TotalCostAverage { get; set; }
        public Nullable<decimal> TotalLastCost { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> NetPricFromInvBeforCurr { get; set; }
        public Nullable<decimal> TotalCostAveragBeforCurr { get; set; }
        public Nullable<decimal> TotalLastCostBeforCurr { get; set; }
        public Nullable<int> TermCostCenterId { get; set; }
        public Nullable<decimal> TermCostCenterValue { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public string Postedby { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<int> PaidDocId { get; set; }
        public Nullable<decimal> NotPaid { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    }
}
