//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_ItemSerialsTransactions
    {
        public int ItemSerialTranId { get; set; }
        public Nullable<int> ItemSerialId { get; set; }
        public string TableCode { get; set; }
        public Nullable<int> TableEntityId { get; set; }
        public Nullable<bool> IsInOrOut { get; set; }
        public Nullable<int> StorePartId { get; set; }
    }
}
