//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ms_ItemPartition
    {
        public int ItemPartId { get; set; }
        public Nullable<int> ItemCardId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> StorePartId { get; set; }
        public Nullable<int> LotNumberExpiryId { get; set; }
        public Nullable<decimal> QtyPartiation { get; set; }
        public Nullable<decimal> QtyInNotebook { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<int> PurchaseNumber { get; set; }
        public Nullable<decimal> FIFOCost { get; set; }
        public Nullable<decimal> LIFOCost { get; set; }
        public Nullable<decimal> CoastAverage { get; set; }
        public string BatchNumberFifoOrLifo { get; set; }
        public Nullable<decimal> VarianceQty { get; set; }
        public Nullable<decimal> ReservedQty { get; set; }
        public Nullable<decimal> RequestedQty { get; set; }
        public Nullable<decimal> SaleNotDelivered { get; set; }
        public Nullable<decimal> PurNotReceived { get; set; }
        public Nullable<decimal> QtyOutWithoutBalance { get; set; }
        public Nullable<decimal> QtyInWithoutCost { get; set; }
        public Nullable<decimal> SalesOrder { get; set; }
        public Nullable<decimal> PurchaseOrder { get; set; }
        public Nullable<decimal> WithoutCost { get; set; }
        public Nullable<decimal> ItemLimit { get; set; }
        public Nullable<decimal> ItemMax { get; set; }
        public Nullable<long> TVersion { get; set; }
        public string TType { get; set; }
    }
}
