//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ms_ItemUnitPackingJoin
    {
        public int ItemPackSizeId { get; set; }
        public Nullable<int> ItemCardId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> PackSizeId { get; set; }
        public Nullable<decimal> QtyInPackage { get; set; }
        public Nullable<decimal> RecomendedQty { get; set; }
        public Nullable<decimal> MineQty { get; set; }
        public Nullable<decimal> MaxQty { get; set; }
        public Nullable<decimal> MaxWheight { get; set; }
        public string Remarks1 { get; set; }
        public string Remarks2 { get; set; }
        public string Remarks3 { get; set; }
    }
}
