//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ms_ItemStartQty
    {
        public int StartQtyId { get; set; }
        public Nullable<int> ItemCardId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> StorePartId { get; set; }
        public Nullable<int> ItemAtrribBatchId { get; set; }
        public Nullable<int> ItemPatchPartitionId { get; set; }
        public Nullable<int> ItemPartId { get; set; }
        public Nullable<decimal> QtyPartiation { get; set; }
        public Nullable<decimal> QtyInNotebook { get; set; }
    }
}
