//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_ItemVendors
    {
        public int ItemVendorId { get; set; }
        public Nullable<int> ItemCardId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<bool> IsBasicVendor { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<decimal> UnitRate { get; set; }
        public string Quantity1 { get; set; }
        public string Price1 { get; set; }
        public string Quantity2 { get; set; }
        public string Price2 { get; set; }
        public string Quantity3 { get; set; }
        public string Price3 { get; set; }
        public string Quantity4 { get; set; }
        public string Price4 { get; set; }
        public string Quantity5 { get; set; }
        public string Price5 { get; set; }
        public string Quantity6 { get; set; }
        public string Price6 { get; set; }
        public string Quantity7 { get; set; }
        public string Price7 { get; set; }
        public string Quantity8 { get; set; }
        public string Price8 { get; set; }
        public string Quantity9 { get; set; }
        public string Price9 { get; set; }
        public string Quantity10 { get; set; }
        public string Price10 { get; set; }
    }
}
