//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ms_ItemCardOffers
    {
        public int OfferItemId { get; set; }
        public Nullable<int> ItemCardId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<decimal> BasicQuantity { get; set; }
        public Nullable<int> GiftItemCardId { get; set; }
        public Nullable<int> GiftUnitId { get; set; }
        public Nullable<decimal> GiftQuantity { get; set; }
        public Nullable<bool> IsGiftDiscount { get; set; }
        public Nullable<bool> IsDiscountPercent { get; set; }
        public Nullable<decimal> GiftDiscount { get; set; }
        public Nullable<decimal> PriceAfterDisc { get; set; }
        public Nullable<bool> IsReplace { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
    }
}
