//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ms_PosItemCategory
    {
        public int PosItemCategoryId { get; set; }
        public Nullable<int> ItemCategoryId { get; set; }
        public Nullable<bool> UseItemName { get; set; }
        public Nullable<bool> UseItemImg { get; set; }
        public Nullable<bool> UseItemCode { get; set; }
        public Nullable<bool> UseItemBarcode { get; set; }
    }
}
