//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_Partition
    {
        public int StorePartId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string PartCode { get; set; }
        public string PartDescA { get; set; }
        public string PartDescE { get; set; }
        public string Remarks { get; set; }
        public string StoreKeeper { get; set; }
        public string Tel { get; set; }
        public string Address { get; set; }
        public string Fax { get; set; }
        public string strCustm2 { get; set; }
        public string strCustm3 { get; set; }
        public string strCustm4 { get; set; }
        public string strCustm5 { get; set; }
        public string strCustm6 { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<decimal> X { get; set; }
        public Nullable<decimal> Y { get; set; }
        public Nullable<decimal> Z { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<bool> SharedPartition { get; set; }
    }
}
