//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ms_PurchaseInvoiceCostReceived
    {
        public int PurNoCostStockId { get; set; }
        public Nullable<int> PurInvId { get; set; }
        public Nullable<int> StockRecId { get; set; }
        public string Remarks { get; set; }
    }
}
