//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_StockTranItemCard
    {
        public int TrItenCardId { get; set; }
        public Nullable<int> TranId { get; set; }
        public Nullable<int> ItemCardId { get; set; }
        public Nullable<int> PartFrom { get; set; }
        public Nullable<int> PartTo { get; set; }
        public Nullable<int> FollowCollectionId { get; set; }
        public Nullable<int> ItemIdToFollow { get; set; }
        public Nullable<int> LotNumberExpiryId { get; set; }
        public Nullable<int> ScaleCardId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<decimal> UnitRate { get; set; }
        public Nullable<byte> ItemType { get; set; }
        public string BarCode { get; set; }
        public string BatchNumberFifoOrLifo { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> QtyBeforRate { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<decimal> ValueRate { get; set; }
        public Nullable<bool> IsCollection { get; set; }
        public Nullable<decimal> FIFOCost { get; set; }
        public Nullable<decimal> FIFOCostUnit { get; set; }
        public Nullable<decimal> LIFOCost { get; set; }
        public Nullable<decimal> LIFOCostUnit { get; set; }
        public Nullable<decimal> CoastAverage { get; set; }
        public Nullable<decimal> CoastAverageUnit { get; set; }
        public Nullable<decimal> LastCost { get; set; }
        public Nullable<decimal> LastCostUnit { get; set; }
        public Nullable<decimal> ExpenseShare { get; set; }
        public Nullable<decimal> ExpenseShareUnit { get; set; }
        public Nullable<decimal> PriceAfterExpense { get; set; }
        public Nullable<decimal> PriceAfterExpenseUnit { get; set; }
        public Nullable<decimal> PriceAfterCurr { get; set; }
        public Nullable<decimal> PriceAfterCurrUnit { get; set; }
        public Nullable<decimal> ExpenseShareAfterCurr { get; set; }
        public Nullable<decimal> ExpenseShareAfterCurrUnit { get; set; }
        public Nullable<decimal> PriceAfterExpenseAfterCurr { get; set; }
        public Nullable<decimal> PriceAfterExpensAfterCurrUnit { get; set; }
        public string Remarks { get; set; }
        public string Remarks1 { get; set; }
        public string Remarks2 { get; set; }
        public string Remarks3 { get; set; }
        public Nullable<int> ItemAtrribBatchId { get; set; }
        public string ItemCardDesc { get; set; }
        public string ItemCardDescE { get; set; }
    }
}
