//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_StockReceiptItemCard
    {
        public int StockRecItemCardId { get; set; }
        public Nullable<int> StockRecId { get; set; }
        public Nullable<int> ItemCardId { get; set; }
        public Nullable<int> ItemAtrribBatchId { get; set; }
        public Nullable<int> InvItemCardId { get; set; }
        public Nullable<int> RetPurchItemCardId { get; set; }
        public Nullable<int> jobGoStockId { get; set; }
        public Nullable<int> jobProductId { get; set; }
        public Nullable<int> jobScrapId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> StorePartId { get; set; }
        public Nullable<int> FollowCollectionId { get; set; }
        public Nullable<int> ItemIdToFollow { get; set; }
        public Nullable<int> LotNumberExpiryId { get; set; }
        public Nullable<int> ScaleCardId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<decimal> UnitRate { get; set; }
        public Nullable<int> BillOfMaterialId { get; set; }
        public Nullable<byte> ItemType { get; set; }
        public string BarCode { get; set; }
        public string BatchNumberFifoOrLifo { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> QtyBeforRate { get; set; }
        public Nullable<decimal> QuantityIn { get; set; }
        public Nullable<decimal> QtyInBeforRate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PriceAfterRate { get; set; }
        public Nullable<bool> IsBonus { get; set; }
        public bool FireTriger { get; set; }
        public Nullable<bool> IsCollection { get; set; }
        public Nullable<decimal> ExpenseShare { get; set; }
        public Nullable<decimal> ExpenseShareUnit { get; set; }
        public Nullable<decimal> PriceAfterExpense { get; set; }
        public Nullable<decimal> PriceAfterExpenseUnit { get; set; }
        public Nullable<decimal> PriceAfterCurr { get; set; }
        public Nullable<decimal> PriceAfterCurrUnit { get; set; }
        public Nullable<decimal> ExpenseShareAfterCurr { get; set; }
        public Nullable<decimal> ExpenseShareAfterCurrUnit { get; set; }
        public Nullable<decimal> PriceAfterExpenseAfterCurr { get; set; }
        public Nullable<decimal> PriceAfterExpensAfterCurrUnit { get; set; }
        public Nullable<byte> Satus { get; set; }
        public Nullable<decimal> FIFOCost { get; set; }
        public Nullable<decimal> FIFOCostUnit { get; set; }
        public Nullable<decimal> LIFOCost { get; set; }
        public Nullable<decimal> LIFOCostUnit { get; set; }
        public Nullable<decimal> CoastAverage { get; set; }
        public Nullable<decimal> CoastAverageUnit { get; set; }
        public string Remarks { get; set; }
        public string Remarks1 { get; set; }
        public string Remarks2 { get; set; }
        public string Remarks3 { get; set; }
        public string ItemCardDesc { get; set; }
        public string ItemCardDescE { get; set; }
        public Nullable<int> IsNoCostDeliver { get; set; }
        public Nullable<bool> DeliverNoCostExecut { get; set; }
        public Nullable<int> AId { get; set; }
        public string DBTableName { get; set; }
        public Nullable<int> DBTableId { get; set; }
        public string AccountTableName { get; set; }
        public Nullable<byte> RectSourceType { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> RectSourceTypeId { get; set; }
    }
}
