//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ms_SalesInvoiceQualityMissedItems
    {
        public int QualitySaleDelMissedId { get; set; }
        public Nullable<int> ItemDeliverId { get; set; }
        public Nullable<int> InvId { get; set; }
        public Nullable<int> ItemCardId { get; set; }
        public Nullable<int> ItemAtrribBatchId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> StorePartId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<decimal> UnitRate { get; set; }
        public Nullable<byte> ItemType { get; set; }
        public string BarCode { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> QtyBeforRate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PriceAfterRate { get; set; }
        public string EmpId { get; set; }
        public string Remarks1 { get; set; }
        public string Remarks2 { get; set; }
    }
}
