//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ms_SalesInvoiceQualityDeliveryDocs
    {
        public int QualitySaleDelId { get; set; }
        public Nullable<int> ItemDeliverId { get; set; }
        public Nullable<int> InvId { get; set; }
        public string Remarks1 { get; set; }
        public string Remarks2 { get; set; }
    }
}
