//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ms_Terms
    {
        public int TermId { get; set; }
        public string TermCode { get; set; }
        public string TermName { get; set; }
        public Nullable<byte> TermType { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<bool> SystemIssuedOnly { get; set; }
        public Nullable<int> JournalEntryBookId { get; set; }
        public Nullable<int> JournalEntryTermId { get; set; }
        public Nullable<int> InventoryBookId { get; set; }
        public Nullable<int> InventoryTermId { get; set; }
        public Nullable<bool> IsOpenningTerm { get; set; }
        public Nullable<bool> CashOrCredit { get; set; }
        public Nullable<bool> IsStopped { get; set; }
        public Nullable<bool> IsDefaultTerm { get; set; }
        public Nullable<byte> UseItemTax { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    }
}
