//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ms_TermsDetails
    {
        public int TermDetailId { get; set; }
        public Nullable<int> TermId { get; set; }
        public Nullable<int> AccountIdDebit { get; set; }
        public Nullable<byte> AccountDebitFixed { get; set; }
        public Nullable<int> CostCenterIdDebit { get; set; }
        public Nullable<byte> CostCenterDebitFixed { get; set; }
        public string ValuAccountDebit { get; set; }
        public Nullable<int> AccountIdCredit { get; set; }
        public Nullable<byte> AccountCreditFixed { get; set; }
        public Nullable<int> CostCenterIdCredit { get; set; }
        public Nullable<byte> CostCenterCreditFixed { get; set; }
        public string ValuAccountCredit { get; set; }
        public Nullable<int> AccountIdDisc { get; set; }
        public Nullable<byte> AccountDiscIsFixed { get; set; }
        public Nullable<int> CostCenterIdDisc { get; set; }
        public Nullable<byte> CostCenterDiscIsFixed { get; set; }
        public string ValuAccountDisc { get; set; }
        public Nullable<int> AccountIdCash { get; set; }
        public Nullable<byte> AccountCashIsFixed { get; set; }
        public Nullable<int> CostCenterIdCash { get; set; }
        public Nullable<byte> CostCenterCashIsFixed { get; set; }
        public string ValuAccountCash { get; set; }
        public Nullable<int> AccountIdTax { get; set; }
        public Nullable<byte> AccountTaxIsFixed { get; set; }
        public Nullable<int> CostCenterIdTax { get; set; }
        public Nullable<byte> CostCenterTaxIsFixed { get; set; }
        public string ValuAccountTax { get; set; }
        public Nullable<bool> AccDiscDebitOrCredit { get; set; }
        public Nullable<bool> AccCashDebitOrCredit { get; set; }
        public Nullable<bool> AccTaxDebitOrCredit { get; set; }
        public Nullable<int> AddAccountId1 { get; set; }
        public Nullable<byte> AddAccount1IsFixed { get; set; }
        public Nullable<int> AddCostCenterId1 { get; set; }
        public Nullable<byte> AddCostCenter1IsFixed { get; set; }
        public string ValuAddAccount1 { get; set; }
        public Nullable<int> AddAccountId2 { get; set; }
        public Nullable<byte> AddAccountIsFixed2 { get; set; }
        public Nullable<int> AddCostCenterId2 { get; set; }
        public Nullable<byte> AddCostCenterIsFixed2 { get; set; }
        public string ValuAddAccount2 { get; set; }
        public Nullable<int> AddAccountId3 { get; set; }
        public Nullable<byte> AddAccountIsFixed3 { get; set; }
        public Nullable<int> AddCostCenterId3 { get; set; }
        public Nullable<byte> AddCostCenterIsFixed3 { get; set; }
        public string ValuAddAccount3 { get; set; }
        public Nullable<int> AddAccountId4 { get; set; }
        public Nullable<byte> AddAccountIsFixed4 { get; set; }
        public Nullable<int> AddCostCenterId4 { get; set; }
        public Nullable<byte> AddCostCenterIsFixed4 { get; set; }
        public string ValuAddAccount4 { get; set; }
        public Nullable<int> AddAccountId5 { get; set; }
        public Nullable<byte> AddAccountIsFixed5 { get; set; }
        public Nullable<int> AddCostCenterId5 { get; set; }
        public Nullable<byte> AddCostCenterIsFixed5 { get; set; }
        public string ValuAddAccount5 { get; set; }
        public Nullable<bool> AddAcc1DebitOrCredit { get; set; }
        public Nullable<bool> AddAcc2DebitOrCredit { get; set; }
        public Nullable<bool> AddAcc3DebitOrCredit { get; set; }
        public Nullable<bool> AddAcc4DebitOrCredit { get; set; }
        public Nullable<bool> AddAcc5DebitOrCredit { get; set; }
        public Nullable<bool> AnalaticalCodeMust { get; set; }
    }
}
