//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ms_WeightcardItems
    {
        public int WeightItemId { get; set; }
        public Nullable<int> ScaleCardId { get; set; }
        public Nullable<int> ItemCardId { get; set; }
        public Nullable<int> LotNumberExpiryId { get; set; }
        public Nullable<int> ItemAtrribBatchId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<decimal> UnitRate { get; set; }
        public string BarCode { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> QtyBeforRate { get; set; }
        public Nullable<decimal> ScaleQuantity { get; set; }
        public Nullable<decimal> ScaleQtyBeforRate { get; set; }
        public string AddField1 { get; set; }
        public string AddField2 { get; set; }
        public string Remarks1 { get; set; }
        public string Remarks2 { get; set; }
    }
}
