//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ms_WeightCard
    {
        public int ScaleCardId { get; set; }
        public Nullable<int> SourceId { get; set; }
        public Nullable<byte> SourceType { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<int> TermId { get; set; }
        public Nullable<int> FinancialIntervalsId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> StorePartId { get; set; }
        public Nullable<int> EquipId { get; set; }
        public Nullable<int> DriverId { get; set; }
        public Nullable<int> EmpId1 { get; set; }
        public Nullable<int> EmpId2 { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> AId { get; set; }
        public int TrNo { get; set; }
        public string ManualTrNo { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
        public Nullable<decimal> WeightQty1 { get; set; }
        public Nullable<decimal> WeightQty2 { get; set; }
        public Nullable<decimal> WheightDiscPercent { get; set; }
        public Nullable<decimal> WeightQtyDiscount { get; set; }
        public Nullable<decimal> WeightQtyDiff { get; set; }
        public Nullable<System.DateTime> Weight1Date { get; set; }
        public Nullable<System.DateTime> Weight1Time { get; set; }
        public Nullable<System.DateTime> Weight2Date { get; set; }
        public Nullable<System.DateTime> Weight2Time { get; set; }
        public Nullable<bool> InOrOut { get; set; }
        public string AddField1 { get; set; }
        public string AddField2 { get; set; }
        public string Remarks1 { get; set; }
        public string Remarks2 { get; set; }
        public string ClosingDoc { get; set; }
        public Nullable<int> ClosingDocId { get; set; }
        public Nullable<bool> IsPrinted { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public string Postedby { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public Nullable<bool> Closed { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<System.DateTime> UncloseDate { get; set; }
        public Nullable<int> ClosedBy { get; set; }
        public Nullable<int> UnclosedBy { get; set; }
        public Nullable<int> PermPrinted { get; set; }
        public Nullable<System.DateTime> PermPrintedAt { get; set; }
        public Nullable<int> TermCostCenterId { get; set; }
        public Nullable<decimal> TermCostCenterValue { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    }
}
