//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsGA_LetterNormalDetail
    {
        public int LetNormDetailId { get; set; }
        public Nullable<int> LetterNormId { get; set; }
        public string BuyerName { get; set; }
        public string BuyerAddress { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string BuyerId { get; set; }
        public Nullable<bool> IsCurrentBuyer { get; set; }
        public Nullable<bool> colSalePrinted { get; set; }
        public Nullable<bool> colQutPrinted { get; set; }
        public Nullable<bool> colLetterPrinted { get; set; }
        public byte[] Image { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public Nullable<int> UserId { get; set; }
        public string AddField1 { get; set; }
        public string AddField2 { get; set; }
    }
}
