//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsGA_MotorSNDetail
    {
        public int MotorSearialID { get; set; }
        public Nullable<int> MotorDocId { get; set; }
        public Nullable<int> LetterNormId { get; set; }
        public Nullable<int> LetterFayumId { get; set; }
        public Nullable<int> MororID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> CapcityId { get; set; }
        public Nullable<int> MachineID { get; set; }
        public string MotorSN { get; set; }
        public string BodySN { get; set; }
        public string Remarks { get; set; }
        public Nullable<byte> BasicSaleType { get; set; }
        public Nullable<bool> LetterType { get; set; }
        public string Model { get; set; }
    }
}
