//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod_ItemAttributesBatche
    {
        public int ItemAtrribBatchId { get; set; }
        public Nullable<int> ItemCardId { get; set; }
        public string ItemBatchCode { get; set; }
        public string ItemBatchName1 { get; set; }
        public string ItemBatchName2 { get; set; }
        public string ItemBatchDesc { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> MultiplyValues { get; set; }
        public Nullable<bool> UseBatchPrice { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public Nullable<decimal> DiscountValue { get; set; }
        public Nullable<int> ParentBatchId { get; set; }
        public Nullable<decimal> BatchLength { get; set; }
        public Nullable<decimal> BatchWidth { get; set; }
        public Nullable<decimal> BatchHieght { get; set; }
        public Nullable<decimal> LengthMeter { get; set; }
        public Nullable<decimal> LengthCentimeter { get; set; }
        public Nullable<decimal> LengthMillimeters { get; set; }
        public Nullable<decimal> WidthMeter { get; set; }
        public Nullable<decimal> WidthCentimeter { get; set; }
        public Nullable<decimal> WidthMillimeters { get; set; }
        public Nullable<decimal> HeightMeter { get; set; }
        public Nullable<decimal> HeightCentimeter { get; set; }
        public Nullable<decimal> HeightMillimeters { get; set; }
        public Nullable<bool> IsStandard { get; set; }
        public Nullable<bool> IsOpened { get; set; }
        public Nullable<bool> IsScrap { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<decimal> QtyInBox { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> Wheight { get; set; }
        public Nullable<bool> IsTempItem { get; set; }
    }
}
