//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod_JobOrderType
    {
        public int JOrderTypeId { get; set; }
        public string Code { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> InDirectExpensesAccountId { get; set; }
        public Nullable<int> CostCenterId { get; set; }
        public Nullable<int> CostCenterId2 { get; set; }
        public Nullable<bool> ItemCostInPrcent { get; set; }
        public Nullable<bool> ExpensesCostInPercent { get; set; }
        public Nullable<bool> JobsCostInPercent { get; set; }
        public Nullable<bool> MachineCostInPercent { get; set; }
        public Nullable<int> FinishedItemStorePartId { get; set; }
        public Nullable<int> MaterialItemStorePartId { get; set; }
        public Nullable<int> GoStockItemStorePartId { get; set; }
        public Nullable<int> ScrapItemStorePartId { get; set; }
        public Nullable<int> FinishedItemRecBookId { get; set; }
        public Nullable<int> MaterialItemDelBookId { get; set; }
        public Nullable<int> GoStockItemRecBookId { get; set; }
        public Nullable<int> ScrapItemRecBookId { get; set; }
        public Nullable<int> FinishedItemRecTermId { get; set; }
        public Nullable<int> MaterialItemDelTermId { get; set; }
        public Nullable<int> GoStockItemRecTermId { get; set; }
        public Nullable<int> ScrapItemRecTermId { get; set; }
        public Nullable<int> FinishedItemRecJournalBookId { get; set; }
        public Nullable<int> MaterialItemDelJournalBookId { get; set; }
        public Nullable<int> GoStockItemRecJournalBookId { get; set; }
        public Nullable<int> ScrapItemRecJournalBookId { get; set; }
        public Nullable<int> FinishedItemRecJournalTermId { get; set; }
        public Nullable<int> MaterialItemDelJournalTermId { get; set; }
        public Nullable<int> GoStockItemRecJournalTermId { get; set; }
        public Nullable<int> ScrapItemRecJournalTermId { get; set; }
        public Nullable<byte> JobOrderMadeFor { get; set; }
        public Nullable<decimal> IndirectMaterialCostPrcent { get; set; }
        public Nullable<decimal> IndirectJobsCostPrcent { get; set; }
        public Nullable<decimal> IndirectMachinesCostPrcent { get; set; }
        public Nullable<decimal> IndirectCostPrcent { get; set; }
        public string Remark { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    }
}
