//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod_JobOrderEquipCostDocDetail
    {
        public int JOrderEquipDocDetailId { get; set; }
        public Nullable<int> JOrderEquipDocId { get; set; }
        public Nullable<int> EquipId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<System.DateTime> FromTime { get; set; }
        public Nullable<System.DateTime> ToTime { get; set; }
        public Nullable<decimal> ExecutTime { get; set; }
        public Nullable<decimal> CostHour { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
    }
}
