//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod_BillOfMaterialItems
    {
        public int BillItemsId { get; set; }
        public int BillOfMaterialId { get; set; }
        public Nullable<int> ItemCardId { get; set; }
        public Nullable<int> ItemAtrribBatchId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<decimal> UnitRate { get; set; }
        public string BarCode { get; set; }
        public Nullable<decimal> QtyBeforRate { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> MaterialProductPercent { get; set; }
        public Nullable<decimal> ProductQtyBeforRate { get; set; }
        public Nullable<decimal> ProductQuantity { get; set; }
        public Nullable<decimal> ScrapQtyBeforRate { get; set; }
        public Nullable<decimal> ScrapQuantity { get; set; }
        public Nullable<int> ProductionUnitId { get; set; }
        public Nullable<decimal> ProductionUnitRate { get; set; }
        public string Remarks { get; set; }
        public string Remarks1 { get; set; }
        public string Remarks2 { get; set; }
        public string Remarks3 { get; set; }
    }
}
