//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod_Equipments
    {
        public int EquipId { get; set; }
        public string EquipCode { get; set; }
        public string EquipName1 { get; set; }
        public string EquipName2 { get; set; }
        public string JDesc { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> StandardMonthlyCost { get; set; }
        public Nullable<byte> StandardHolyDays { get; set; }
        public Nullable<decimal> StandardDailyCost { get; set; }
        public Nullable<decimal> StandardDailyWorkHours { get; set; }
        public Nullable<decimal> StandardHourlyCost { get; set; }
        public Nullable<int> NumberAvailable { get; set; }
        public Nullable<decimal> TimeRate { get; set; }
        public Nullable<int> BasUnitId { get; set; }
        public Nullable<decimal> QtyPerUnit { get; set; }
        public Nullable<decimal> IsScale { get; set; }
        public Nullable<decimal> MaxWeight { get; set; }
        public Nullable<decimal> MinWeight { get; set; }
        public string TechnicalSpecs { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    }
}
