//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod_ProductionLine
    {
        public int ProLineId { get; set; }
        public Nullable<int> ProdLinCode { get; set; }
        public string ProdLinName1 { get; set; }
        public string ProdLinName2 { get; set; }
        public string ProdLinDesc { get; set; }
        public Nullable<int> ItemCardId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> ItemAtrribBatchId { get; set; }
        public Nullable<decimal> StandardQty { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    }
}
