//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod_AttributeValue
    {
        public int AttribValuId { get; set; }
        public Nullable<int> AttributId { get; set; }
        public string AttributValuName1 { get; set; }
        public string AttributValuName2 { get; set; }
        public string AttributValue { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> LengthMeter { get; set; }
        public Nullable<decimal> LengthCentimeter { get; set; }
        public Nullable<decimal> LengthMillimeters { get; set; }
        public Nullable<decimal> WidthMeter { get; set; }
        public Nullable<decimal> WidthCentimeter { get; set; }
        public Nullable<decimal> WidthMillimeters { get; set; }
        public Nullable<decimal> HeightMeter { get; set; }
        public Nullable<decimal> HeightCentimeter { get; set; }
        public Nullable<decimal> HeightMillimeters { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    }
}
