//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proj_ProjectItemsVendors
    {
        public int ProjectItemsVendorId { get; set; }
        public Nullable<int> ProjectItemsId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<byte> VendorRate { get; set; }
    }
}
