//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proj_ReservInstallments
    {
        public int ReservInstallId { get; set; }
        public Nullable<int> ReservId { get; set; }
        public Nullable<int> Serial { get; set; }
        public Nullable<int> InstallTempDetailId { get; set; }
        public Nullable<int> PayTypeId { get; set; }
        public Nullable<int> ResourceId { get; set; }
        public Nullable<byte> ResourceType { get; set; }
        public Nullable<int> ResourceAccountId { get; set; }
        public Nullable<int> ProjUnitServiceId { get; set; }
        public Nullable<int> UnitServId { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<decimal> InstallValu { get; set; }
        public Nullable<decimal> PaidCash { get; set; }
        public Nullable<decimal> PaidCheques { get; set; }
        public Nullable<decimal> PaidBankDeposit { get; set; }
        public Nullable<decimal> NotPaid { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public Nullable<int> DelayDays { get; set; }
        public Nullable<decimal> DelayFine { get; set; }
        public Nullable<int> RectId { get; set; }
        public string Remarks1 { get; set; }
        public string Remarks2 { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string DeletReason { get; set; }
    }
}
