//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proj_ProjUnits
    {
        public int ProjUnitId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> UnittypeId { get; set; }
        public Nullable<int> UnitStatId { get; set; }
        public Nullable<int> UnitDegreeId { get; set; }
        public Nullable<int> UnFinLevelId { get; set; }
        public Nullable<int> UnitInsurstatId { get; set; }
        public Nullable<int> ParkingId { get; set; }
        public Nullable<int> ContractTypeId { get; set; }
        public Nullable<int> RentCaseId { get; set; }
        public Nullable<int> TermId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public string Code { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public Nullable<int> RoomCount { get; set; }
        public Nullable<int> FloorNumber { get; set; }
        public Nullable<long> WaterCounter { get; set; }
        public Nullable<long> ElectricityCounter { get; set; }
        public Nullable<bool> CalcAllMeters { get; set; }
        public Nullable<decimal> BuildingArea { get; set; }
        public Nullable<decimal> BuildingMeterPrice { get; set; }
        public Nullable<decimal> UnitArea { get; set; }
        public Nullable<decimal> UnitMeterPrice { get; set; }
        public Nullable<decimal> EstimatedUnitArea { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<bool> CommissionIsPercent { get; set; }
        public Nullable<decimal> CommissionValue { get; set; }
        public Nullable<System.DateTime> ExpectedDeliveryDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> UnitStartDate { get; set; }
        public Nullable<System.DateTime> UnitExpectedStartDate { get; set; }
        public Nullable<decimal> ParkArea { get; set; }
        public Nullable<decimal> ParkMeterPrice { get; set; }
        public Nullable<decimal> RoofArea { get; set; }
        public Nullable<decimal> RoofMeterPrice { get; set; }
        public Nullable<decimal> GardenArea { get; set; }
        public Nullable<decimal> GardenMeterPrice { get; set; }
        public Nullable<decimal> BaseMentArea { get; set; }
        public Nullable<decimal> BasementMeterPrice { get; set; }
        public Nullable<bool> CanSaleUnits { get; set; }
        public Nullable<bool> CanRentUnits { get; set; }
        public Nullable<bool> ProjectStopped { get; set; }
        public Nullable<bool> Sold { get; set; }
        public string ContractDocNo { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public Nullable<bool> Reserved { get; set; }
        public Nullable<System.DateTime> ReserveDate { get; set; }
        public string ReserveDocNo { get; set; }
        public Nullable<bool> Rented { get; set; }
        public Nullable<System.DateTime> RentDate { get; set; }
        public string RentDocNo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    }
}
