//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proj_ProjInsurance
    {
        public int ProjInsuranceId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> BuildInsurStatId { get; set; }
        public Nullable<int> InsurCovTypeId { get; set; }
        public Nullable<decimal> InsuranceValue { get; set; }
        public string Remarks1 { get; set; }
        public string Remarks2 { get; set; }
    }
}
