//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proj_UnitReservation
    {
        public int ReservId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<int> TermId { get; set; }
        public Nullable<int> FinancialIntervalsId { get; set; }
        public Nullable<int> InstallTempId { get; set; }
        public Nullable<int> InstallId { get; set; }
        public Nullable<int> ContractTypeId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<bool> IsCustBalancInstall { get; set; }
        public Nullable<decimal> CustomerBalace { get; set; }
        public Nullable<int> AId { get; set; }
        public Nullable<int> TrNo { get; set; }
        public string ManualTrNo { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> ContractTrNo { get; set; }
        public Nullable<int> ContractBookId { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> PayStartDate { get; set; }
        public Nullable<int> ProjUnitId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> SalesEmpId { get; set; }
        public Nullable<decimal> UnitMeterPrice { get; set; }
        public Nullable<decimal> UnitArea { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<bool> PaidInCash { get; set; }
        public Nullable<decimal> ActualSalesPrice { get; set; }
        public Nullable<decimal> TotalInstallments { get; set; }
        public Nullable<decimal> NotPaidInstallments { get; set; }
        public Nullable<decimal> CommissionPercent { get; set; }
        public Nullable<decimal> CommissionValue { get; set; }
        public Nullable<decimal> LeavePercent { get; set; }
        public Nullable<decimal> LeaveValue { get; set; }
        public Nullable<decimal> FeesPercent { get; set; }
        public Nullable<decimal> FeesValue { get; set; }
        public Nullable<decimal> FinishMeterPrice { get; set; }
        public Nullable<decimal> FinishValue { get; set; }
        public Nullable<decimal> DiscPercent { get; set; }
        public Nullable<decimal> DiscValue { get; set; }
        public Nullable<decimal> TotalServices { get; set; }
        public Nullable<decimal> TotalUnitArea { get; set; }
        public Nullable<bool> IsContract { get; set; }
        public Nullable<byte> RoundType { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Closed { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<System.DateTime> UncloseDate { get; set; }
        public Nullable<int> ClosedBy { get; set; }
        public Nullable<decimal> NotPaid { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public string Postedby { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public Nullable<int> TermCostCenterId { get; set; }
        public Nullable<decimal> TermCostCenterValue { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    }
}
