//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proj_ProjUnitSubUnits
    {
        public int SubUnitId { get; set; }
        public int ProjUnitId { get; set; }
        public int SubUnittypeId { get; set; }
        public Nullable<bool> CalcByMeter { get; set; }
        public Nullable<decimal> MetersCount { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> MeterPrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public string RemarksA { get; set; }
        public string RemarksE { get; set; }
    }
}
