//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proj_ProjItemEmpTaskJoin
    {
        public int ProjItemEmpTaskId { get; set; }
        public Nullable<int> ProjItemEmpId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<decimal> ExpectItemPercent { get; set; }
        public Nullable<decimal> ExpectItemValue { get; set; }
        public Nullable<decimal> ActualItemPercentExpense { get; set; }
        public Nullable<decimal> ActualItemExpenseValue { get; set; }
        public Nullable<decimal> FinishPercent { get; set; }
        public string Remarks1 { get; set; }
        public string Remarks2 { get; set; }
    }
}
