//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proj_Projects
    {
        public int ProjectId { get; set; }
        public Nullable<int> BuildTypeId { get; set; }
        public Nullable<int> BuildStatusId { get; set; }
        public Nullable<int> BuildDegreeId { get; set; }
        public Nullable<int> BuildFinishLevelId { get; set; }
        public Nullable<int> LandId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> SubRegionClassId { get; set; }
        public Nullable<int> ContractTypeId { get; set; }
        public Nullable<int> PostalCodId { get; set; }
        public Nullable<int> RentCaseId { get; set; }
        public Nullable<int> CostCenterId1 { get; set; }
        public Nullable<int> CostCenterId2 { get; set; }
        public Nullable<int> CostCenterId3 { get; set; }
        public Nullable<int> AId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName1 { get; set; }
        public string ProjectName2 { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ParentProjectId { get; set; }
        public Nullable<bool> ProjectStopped { get; set; }
        public Nullable<int> ProjectStoppedbyUserId { get; set; }
        public Nullable<bool> CalcAllMeters { get; set; }
        public Nullable<bool> CanSaleUnits { get; set; }
        public Nullable<bool> CanRentUnits { get; set; }
        public string StreetNo { get; set; }
        public string LandNo { get; set; }
        public Nullable<int> FloorsCount { get; set; }
        public Nullable<int> FloorUnitCount { get; set; }
        public Nullable<int> FirstFloorUnitCount { get; set; }
        public Nullable<int> LastFloorUnitCount { get; set; }
        public Nullable<long> WaterCounter { get; set; }
        public Nullable<long> ElectricityCounter { get; set; }
        public Nullable<decimal> Landarea { get; set; }
        public Nullable<decimal> BuildingArea { get; set; }
        public Nullable<decimal> LandMeterPrice { get; set; }
        public Nullable<decimal> BuildingMeterPrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string NorthBoundary { get; set; }
        public string SouthBoundary { get; set; }
        public string WestBoundary { get; set; }
        public string EastBoundary { get; set; }
        public Nullable<System.DateTime> ExpectedDeliveryDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public Nullable<System.DateTime> ProjectStartDate { get; set; }
        public Nullable<System.DateTime> ProjectExpectedStartDate { get; set; }
        public Nullable<byte> FundSource { get; set; }
        public Nullable<decimal> PaidCapital { get; set; }
        public Nullable<decimal> ProjectValue { get; set; }
        public Nullable<decimal> PaidCapitalPercent { get; set; }
        public Nullable<decimal> ExpectedExpense { get; set; }
        public Nullable<decimal> ActualExpense { get; set; }
        public Nullable<decimal> ActualExpensePercent { get; set; }
        public Nullable<decimal> RemainExpense { get; set; }
        public Nullable<decimal> RemainExpensePercent { get; set; }
        public Nullable<decimal> CompanySharePercent { get; set; }
        public Nullable<bool> CommissionIsPercent { get; set; }
        public Nullable<decimal> CommissionValue { get; set; }
        public Nullable<int> ProjectManagerId { get; set; }
        public Nullable<decimal> CompanyShare { get; set; }
        public Nullable<decimal> ParkArea { get; set; }
        public Nullable<decimal> ParkMeterPrice { get; set; }
        public Nullable<decimal> RoofArea { get; set; }
        public Nullable<decimal> RoofMeterPrice { get; set; }
        public Nullable<decimal> GardenArea { get; set; }
        public Nullable<decimal> GardenMeterPrice { get; set; }
        public Nullable<decimal> BaseMentArea { get; set; }
        public Nullable<decimal> BasementMeterPrice { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    }
}
