//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proj_Accounts
    {
        public int ProjectAccId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<decimal> Value { get; set; }
    }
}
