//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proj_UnitHistoryLog
    {
        public int ProjUnitHistoryId { get; set; }
        public Nullable<int> ProjUnitId { get; set; }
        public string TableCode { get; set; }
        public string TableEntityIdName { get; set; }
        public Nullable<long> TableEntityId { get; set; }
        public string LogActionDesc { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
