//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proj_RealItems
    {
        public int ProjectRealItemId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> ItemCardId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public string AttributeCode { get; set; }
        public string AttributeName { get; set; }
        public Nullable<decimal> SuggestPrice { get; set; }
        public Nullable<decimal> RealCost { get; set; }
    }
}
