//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quality_ItemRecieveDetails
    {
        public int ProdItemRecDetailId { get; set; }
        public Nullable<int> ProdItemRecId { get; set; }
        public Nullable<int> ItemCardId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<decimal> UnitRate { get; set; }
        public Nullable<byte> ItemType { get; set; }
        public string BarCode { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> QtyBeforRate { get; set; }
        public Nullable<decimal> ExecutedQtyBeforRate { get; set; }
        public Nullable<decimal> ExecutedQty { get; set; }
        public Nullable<decimal> MissedQtyBeforRate { get; set; }
        public Nullable<decimal> MissedQuantity { get; set; }
        public string ItemCardDesc { get; set; }
        public string ItemCardDescE { get; set; }
        public string Remarks { get; set; }
        public string Remarks2 { get; set; }
    }
}
