//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quality_ItemRecPackages
    {
        public int ItemRecPackId { get; set; }
        public Nullable<int> ItemRecQualityId { get; set; }
        public Nullable<int> WorkOrderId { get; set; }
        public string Code { get; set; }
        public Nullable<int> PackageSerial { get; set; }
        public Nullable<long> AlterSerial { get; set; }
    }
}
