//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quality_ItemRecCheckDetail
    {
        public int ItemRecQualityDetailId { get; set; }
        public Nullable<int> ItemRecQualityId { get; set; }
        public Nullable<int> ItemCardId { get; set; }
        public Nullable<int> QualityCatId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<decimal> UnitRate { get; set; }
        public Nullable<byte> ItemType { get; set; }
        public string BarCode { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> QtyBeforRate { get; set; }
        public Nullable<decimal> ExecutedQtyBeforRate { get; set; }
        public Nullable<decimal> ExecutedQty { get; set; }
        public Nullable<decimal> MissedQtyBeforRate { get; set; }
        public Nullable<decimal> MissedQuantity { get; set; }
        public Nullable<decimal> PriceNormal { get; set; }
        public Nullable<decimal> TotalNormal { get; set; }
        public Nullable<decimal> PriceDoubleClean { get; set; }
        public Nullable<decimal> TotalDoubleClean { get; set; }
        public string ItemCardDesc { get; set; }
        public string ItemCardDescE { get; set; }
        public string Remarks { get; set; }
        public string Remarks2 { get; set; }
        public Nullable<decimal> NormalQtyBeforRate { get; set; }
        public Nullable<decimal> NormalQuantity { get; set; }
        public Nullable<decimal> DoublCheckQtyBeforRate { get; set; }
        public Nullable<decimal> DoublCheckQuantity { get; set; }
        public Nullable<decimal> RejectedQtyBeforRate { get; set; }
        public Nullable<decimal> RejectedQuantity { get; set; }
    }
}
