//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sr_Accomodation
    {
        public int AccomodationId { get; set; }
        public Nullable<int> TripId { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> HotelId { get; set; }
        public Nullable<byte> AccomodationType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Remarks { get; set; }
    }
}
