//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sr_Hotels
    {
        public int HotelId { get; set; }
        public string HotelCode { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public Nullable<byte> Stars { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> ElevatorNum { get; set; }
        public Nullable<int> RoomSingleCount { get; set; }
        public Nullable<decimal> RoomSingleCost { get; set; }
        public Nullable<int> DoubleRoomCount { get; set; }
        public Nullable<decimal> DoubleRoomCost { get; set; }
        public Nullable<int> TribleRoomCount { get; set; }
        public Nullable<decimal> TribleRoomCost { get; set; }
        public Nullable<int> QuadRoomCount { get; set; }
        public Nullable<decimal> QuadRoomCost { get; set; }
        public Nullable<int> SuitRoomCount { get; set; }
        public Nullable<decimal> SuitRoomCost { get; set; }
        public Nullable<int> SpecialRoomCount { get; set; }
        public Nullable<decimal> SpecialRoomCost { get; set; }
        public Nullable<bool> SupportFB { get; set; }
        public Nullable<bool> SupportHB { get; set; }
        public Nullable<bool> SupportBB { get; set; }
        public Nullable<bool> SupportRO { get; set; }
        public Nullable<bool> RoomsWithWC { get; set; }
        public Nullable<decimal> FBCost { get; set; }
        public Nullable<decimal> HBCost { get; set; }
        public Nullable<decimal> BBCost { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Email2 { get; set; }
        public string Email3 { get; set; }
        public string Email4 { get; set; }
        public string Address { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Tel2 { get; set; }
        public string Tel3 { get; set; }
        public string Tel4 { get; set; }
        public string Tel5 { get; set; }
        public string AddField1 { get; set; }
        public string AddField2 { get; set; }
        public string AddField3 { get; set; }
        public string AddField4 { get; set; }
        public string AddField5 { get; set; }
        public string Remark { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    }
}
