//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sr_JobSWages
    {
        public int JobSTechId { get; set; }
        public Nullable<int> JorderId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string EmpCode { get; set; }
        public string EmpName1 { get; set; }
        public Nullable<decimal> TotalHours { get; set; }
        public Nullable<decimal> HourlyCostRate { get; set; }
        public Nullable<decimal> WValue { get; set; }
        public string WDescription { get; set; }
    }
}
