//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sr_ReciptionDetail
    {
        public int RecipDetlId { get; set; }
        public Nullable<int> ReciptionId { get; set; }
        public string CustRequest { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ComID { get; set; }
        public Nullable<byte> Serial { get; set; }
    }
}
