//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sr_ReceptionImages
    {
        public int RecImgId { get; set; }
        public Nullable<int> ReciptionId { get; set; }
        public byte[] Image { get; set; }
        public string ImgDesc { get; set; }
    }
}
