//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sr_TripProgramJoin
    {
        public int TripProgramJoinId { get; set; }
        public Nullable<int> TripId { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string Days { get; set; }
        public string MTSCruze { get; set; }
        public Nullable<byte> Number { get; set; }
    }
}
