//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sr_TaskItem
    {
        public int TskItemId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<int> ItemCardId { get; set; }
        public string HowUse { get; set; }
    }
}
