//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sr_TripAccomDetail
    {
        public int TripAccomDetailId { get; set; }
        public Nullable<int> AccomodationId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string PassPortNo { get; set; }
        public string RoomNo { get; set; }
        public Nullable<int> PersonCount { get; set; }
        public string Remarks { get; set; }
    }
}
