//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sr_TaskEmp
    {
        public int TskTech { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string EmpRole { get; set; }
    }
}
