//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sr_VehicleItemCard
    {
        public int VehclItemPart { get; set; }
        public Nullable<int> ItemCardId { get; set; }
        public Nullable<int> ItemCardIdIsVehicl { get; set; }
        public string Description { get; set; }
    }
}
