//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sr_Vehicles
    {
        public int VehicleId { get; set; }
        public string VehicleCode { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public Nullable<int> InvItemCardId { get; set; }
        public Nullable<int> ItemCardId { get; set; }
        public Nullable<int> InvId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> VehicleTypId { get; set; }
        public Nullable<int> VehicleShapeId { get; set; }
        public Nullable<int> TrafficLineId { get; set; }
        public Nullable<int> WId { get; set; }
        public Nullable<int> DriverId1 { get; set; }
        public Nullable<int> DriverId2 { get; set; }
        public Nullable<int> GarageId { get; set; }
        public Nullable<int> CostCenterId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<bool> IsCompanyCar { get; set; }
        public Nullable<bool> InWarranty { get; set; }
        public string RegNo { get; set; }
        public string BodyNo { get; set; }
        public string MotorNo { get; set; }
        public Nullable<long> StartCounterNo { get; set; }
        public Nullable<long> CounterNo { get; set; }
        public Nullable<int> YearModel { get; set; }
        public string Color { get; set; }
        public string OwnerName { get; set; }
        public string OwnerAddress { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    }
}
