//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sr_VehicleRenalContract
    {
        public int VRentContractId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<int> TermId { get; set; }
        public Nullable<int> FinancialIntervalsId { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public Nullable<int> AId { get; set; }
        public Nullable<int> DriverId1 { get; set; }
        public Nullable<int> DriverId2 { get; set; }
        public Nullable<int> DriverId3 { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> HotelId { get; set; }
        public Nullable<int> TrNo { get; set; }
        public string ManualTrNo { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
        public Nullable<System.DateTime> ExpectedStartDate { get; set; }
        public Nullable<System.DateTime> RealStartDate { get; set; }
        public Nullable<System.DateTime> GetOutDate { get; set; }
        public Nullable<byte> PaymentMethod { get; set; }
        public string HotelRoom { get; set; }
        public Nullable<long> StartCounter { get; set; }
        public Nullable<long> EndCounter { get; set; }
        public Nullable<long> ConsumedCounter { get; set; }
        public Nullable<long> AllowanceCounter { get; set; }
        public Nullable<long> ExtraCounter { get; set; }
        public Nullable<long> DailyCounter { get; set; }
        public Nullable<decimal> FuelIn { get; set; }
        public Nullable<decimal> FuelOut { get; set; }
        public string VisaNo { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> VisaExpiryDate { get; set; }
        public string VisaCode { get; set; }
        public Nullable<decimal> VisaAmount { get; set; }
        public Nullable<bool> VisaApproved { get; set; }
        public Nullable<decimal> InsuranceValue { get; set; }
        public Nullable<decimal> InsuranceValue2 { get; set; }
        public Nullable<int> ContractDays { get; set; }
        public Nullable<decimal> DayPrice { get; set; }
        public Nullable<decimal> InvTotal { get; set; }
        public Nullable<decimal> DeliveryCost { get; set; }
        public Nullable<decimal> DriverCost { get; set; }
        public Nullable<decimal> FuelCost { get; set; }
        public Nullable<decimal> MaintenanceCost { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> NetDue { get; set; }
        public Nullable<decimal> Repaid { get; set; }
        public Nullable<decimal> DiscPercent { get; set; }
        public Nullable<decimal> DiscAmount { get; set; }
        public Nullable<decimal> DiscPercent2 { get; set; }
        public Nullable<decimal> DiscAmount2 { get; set; }
        public Nullable<decimal> DiscPercent3 { get; set; }
        public Nullable<decimal> DiscAmount3 { get; set; }
        public Nullable<decimal> DiscPercent4 { get; set; }
        public Nullable<decimal> DiscAmount4 { get; set; }
        public Nullable<decimal> PriceAfterTax { get; set; }
        public Nullable<decimal> ExpenValue { get; set; }
        public Nullable<decimal> PaidPrice { get; set; }
        public Nullable<decimal> NetPrice { get; set; }
        public Nullable<decimal> Commision { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> NetPriceBeforCurr { get; set; }
        public Nullable<decimal> ExpenValueBeforCurr { get; set; }
        public Nullable<decimal> ExpenValueWithCurr { get; set; }
        public Nullable<decimal> NotPaid { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<decimal> TotalPurchInv { get; set; }
        public Nullable<decimal> TotalPayment { get; set; }
        public Nullable<decimal> TotalPaidReciept { get; set; }
        public Nullable<decimal> TotalSalesInv { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<decimal> TotalCostBeforeCurr { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Email2 { get; set; }
        public string Email3 { get; set; }
        public string Email4 { get; set; }
        public string Address { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Tel2 { get; set; }
        public string Tel3 { get; set; }
        public string Tel4 { get; set; }
        public string Tel5 { get; set; }
        public string AddField1 { get; set; }
        public string AddField2 { get; set; }
        public string AddField3 { get; set; }
        public string AddField4 { get; set; }
        public string AddField5 { get; set; }
        public Nullable<int> TermCostCenterId { get; set; }
        public Nullable<decimal> TermCostCenterValue { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public string Postedby { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public Nullable<bool> Closed { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<System.DateTime> UncloseDate { get; set; }
        public Nullable<int> ClosedBy { get; set; }
        public Nullable<int> UnclosedBy { get; set; }
        public Nullable<int> PermPrinted { get; set; }
        public Nullable<System.DateTime> PermPrintedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    }
}
