//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_SalesPurchaseDetails
    {
        public int StockSalPurchDetailId { get; set; }
        public Nullable<int> StockSalPurchId { get; set; }
        public Nullable<int> StockTranTypId { get; set; }
        public Nullable<int> StockDealersId { get; set; }
        public Nullable<int> DealNo { get; set; }
        public Nullable<System.DateTime> DealTime { get; set; }
        public Nullable<int> StockId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> FixedCommision { get; set; }
        public Nullable<decimal> OtherCommision { get; set; }
        public Nullable<decimal> NetValue { get; set; }
    }
}
