//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_PortfolioAccounts
    {
        public int StockPortAccountsId { get; set; }
        public Nullable<int> StockPortfolioId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<decimal> OpenningBalance { get; set; }
        public Nullable<decimal> CurrentBalance { get; set; }
        public Nullable<bool> Auto { get; set; }
        public Nullable<bool> NoTranEffect { get; set; }
    }
}
