//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_CashTransfer
    {
        public int StockCashTransferId { get; set; }
        public Nullable<int> StockTranTypId { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<int> TermId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> FinancialIntervalsId { get; set; }
        public Nullable<int> FromStockPortfolioId { get; set; }
        public Nullable<int> AccountIdFrom { get; set; }
        public Nullable<int> ToStockPortfolioId { get; set; }
        public Nullable<int> AccountIdTo { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> CurrencyRate { get; set; }
        public int TrNo { get; set; }
        public string ManualTrNo { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
        public Nullable<System.DateTime> TrTime { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    }
}
