//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_PortfolioStocks
    {
        public int StockPortJoinId { get; set; }
        public Nullable<int> StockPortfolioId { get; set; }
        public Nullable<int> StockId { get; set; }
        public Nullable<int> StockQuantity { get; set; }
        public Nullable<decimal> CostAverage { get; set; }
    }
}
