//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_FlexLists
    {
        public int FlexListId { get; set; }
        public Nullable<int> NamingId { get; set; }
        public string FlexCode { get; set; }
        public string FlexName1 { get; set; }
        public string FlexName2 { get; set; }
        public string TableCode { get; set; }
        public string FieldCode { get; set; }
        public string Value1 { get; set; }
        public string Value2 { get; set; }
        public string Value3 { get; set; }
        public string Value4 { get; set; }
        public string Value5 { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public string Culture { get; set; }
        public Nullable<bool> AllLanguages { get; set; }
    }
}
