//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_AnalyticalCodes
    {
        public int AId { get; set; }
        public Nullable<int> ParentAId { get; set; }
        public Nullable<int> CodeLevel { get; set; }
        public Nullable<byte> CodeLevelType { get; set; }
        public string Code { get; set; }
        public string DescA { get; set; }
        public string DescE { get; set; }
        public Nullable<bool> Stopped { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> CostCenterId { get; set; }
        public Nullable<int> AssetId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<int> BSPartnerId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> ItemCardId { get; set; }
        public Nullable<int> AccomulatAId { get; set; }
        public string AddField1 { get; set; }
        public string AddField2 { get; set; }
        public string AddField3 { get; set; }
        public string AddField4 { get; set; }
        public string AddField5 { get; set; }
        public string AddField6 { get; set; }
        public string AddField7 { get; set; }
        public string AddField8 { get; set; }
        public string AddField9 { get; set; }
        public string AddField10 { get; set; }
        public string AddField11 { get; set; }
        public string AddField12 { get; set; }
        public string AddField13 { get; set; }
        public string AddField14 { get; set; }
        public string AddField15 { get; set; }
        public string AddField16 { get; set; }
        public string AddField17 { get; set; }
        public string AddField18 { get; set; }
        public string AddField19 { get; set; }
        public string AddField20 { get; set; }
        public string AddField21 { get; set; }
        public string AddField22 { get; set; }
        public string AddField23 { get; set; }
        public string AddField24 { get; set; }
        public string AddField25 { get; set; }
        public string RemarksA { get; set; }
        public string RemarksE { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    }
}
