//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Counter
    {
        public int CounterId { get; set; }
        public string TrIdName { get; set; }
        public Nullable<int> Counter { get; set; }
        public Nullable<int> BookId { get; set; }
    }
}
