//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_FinancialYears
    {
        public int FinancialYearsId { get; set; }
        public Nullable<int> FinancialYearsCode { get; set; }
        public string FinancialYearNameA { get; set; }
        public string FinancialYearNameE { get; set; }
        public Nullable<System.DateTime> StartingFrom { get; set; }
        public string StartingFromHijri { get; set; }
        public Nullable<System.DateTime> EndTo { get; set; }
        public string EndToHijri { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public string ClosingDateHijri { get; set; }
        public string YearState { get; set; }
        public Nullable<int> NoOfIntervals { get; set; }
        public Nullable<bool> YearType { get; set; }
        public Nullable<byte> SubPeriodsType { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string StopReason { get; set; }
        public Nullable<int> StoppedByUserId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    }
}
