//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_City
    {
        public int SysCityID { get; set; }
        public string cityName { get; set; }
        public string CountryCode { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
    }
}
