//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_FinancialIntervals
    {
        public int FinancialIntervalsId { get; set; }
        public string FinancialIntervalCode { get; set; }
        public string MonthNameA { get; set; }
        public string MonthNameE { get; set; }
        public Nullable<System.DateTime> StartingFrom { get; set; }
        public string StartingFromHijri { get; set; }
        public Nullable<System.DateTime> EndingDate { get; set; }
        public string EndToHijri { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsInUse { get; set; }
        public string StopReason { get; set; }
        public Nullable<int> StoppedByUserId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<int> FinancialYearId { get; set; }
    }
}
